"""IRON_DATA_MODEL v0.3 as types, validation, and serialization.

Built Day 13 from three rounds of architecture review. This package is
primitives and rules — construction, validation, serialization, migration,
structural guards — not inference. The factor-graph solver, the estimator,
behaviour models, and the LLM layer are out of scope; where this package
needs a placeholder for one, it is a function that raises
``NotImplementedError`` with a docstring naming what will fill it, never a
stub that silently returns a plausible-looking answer.

Every rule marked STRUCTURAL in the Day-13 prompt is enforced by the type
system or a constructor-time raise, proven by a test that attempts the
violation. See ``tests/test_model_*.py``.
"""

from __future__ import annotations

from src.model.entity import (
    ENTITY_KINDS,
    IDENTITY_CLASSES,
    AnonymousSessionEntity,
    Entity,
    EntityError,
    EntityKind,
    EnrolledEntity,
    FixtureEntity,
    IdentityClass,
    RegisteredAssetEntity,
    TimeVaryingAttribute,
)
from src.model.alert import (
    Alert,
    AlertEmissionEligibleEvent,
    AlertError,
    ExplainabilityError,
    ExplainedAlert,
    ExplainedHop,
    emit_alert,
    explain,
)
from src.model.coverage import (
    AbsenceResult,
    COVERAGE_STATUSES,
    GAP_REASONS,
    Absence,
    CannotEstablish,
    Coverage,
    CoverageError,
    CoverageStatus,
    Gap,
    GapReason,
    Interval,
    Predicate,
    prove_absence,
)
from src.model.envelope import Envelope, EnvelopeCurve, EnvelopeError
from src.model.events import (
    EVENT_SCHEMA_VERSION,
    AlertEligibleEvent,
    EventClassName,
    EventError,
    EventV2,
    EvidenceEligibleEvent,
    HypothesisEvent,
    InferredEvent,
    ObservedEvent,
    PredictedEvent,
    assemble_evidence,
    confirm_prediction,
    event_v2_from_dict,
    event_v2_to_dict,
    raise_alert,
)
from src.model.evidence import (
    COMMITMENT_STATUSES,
    CalibratedProbability,
    CalibrationRecord,
    CommitmentStatus,
    Confidence,
    DerivationStep,
    Evidence,
    EvidenceCommitment,
    EvidenceError,
    UncalibratedScore,
    compute_merkle_root,
)
from src.model.episode import (
    ACTIVITY_LABELS,
    ACTIVITY_SCOPE_KINDS,
    PARTICIPANT_ROLES,
    ActivityLabel,
    ActivityMode,
    ActivityScopeKind,
    Episode,
    EpisodeError,
    Factor,
    Participant,
    ParticipantRole,
    StateGraph,
    StateQuery,
    attach_to_alert,
    attach_to_evidence,
    solve_state,
)
from src.model.frame_of_reference import FrameOfReference
from src.model.measurement import (
    BadgeSwipeMeasurement,
    CameraFrameMeasurement,
    DoorContactMeasurement,
    HRISSyncMeasurement,
    Measurement,
)
from src.model.observation import Observation, ObservationError
from src.model.relationship import (
    CORRECTION_KINDS,
    RELATIONSHIP_BASES,
    ArtifactRegistry,
    Correction,
    CorrectionKind,
    DerivedArtifact,
    Relationship,
    RelationshipBasis,
    RelationshipError,
)
from src.model.uncertainty import ALL_UNCERTAINTY_KINDS, Uncertainty, UncertaintyError
from src.model.ulid import ULID, InvalidULID, generate_ulid
from src.model.world import (
    RigidTransform3D,
    TwinRevError,
    TwinRevTransform,
    TwinRevTransformRegistry,
    WorldPosition,
)

__all__ = [
    "ULID",
    "InvalidULID",
    "generate_ulid",
    "Uncertainty",
    "UncertaintyError",
    "ALL_UNCERTAINTY_KINDS",
    "CameraFrameMeasurement",
    "BadgeSwipeMeasurement",
    "DoorContactMeasurement",
    "HRISSyncMeasurement",
    "Measurement",
    "FrameOfReference",
    "Observation",
    "ObservationError",
    "Entity",
    "EntityError",
    "EntityKind",
    "ENTITY_KINDS",
    "IdentityClass",
    "IDENTITY_CLASSES",
    "AnonymousSessionEntity",
    "EnrolledEntity",
    "RegisteredAssetEntity",
    "FixtureEntity",
    "TimeVaryingAttribute",
    "EnvelopeCurve",
    "Envelope",
    "EnvelopeError",
    "Interval",
    "CoverageStatus",
    "COVERAGE_STATUSES",
    "GapReason",
    "GAP_REASONS",
    "Gap",
    "Coverage",
    "CoverageError",
    "Absence",
    "CannotEstablish",
    "AbsenceResult",
    "Predicate",
    "prove_absence",
    "EVENT_SCHEMA_VERSION",
    "EventClassName",
    "EventError",
    "EventV2",
    "EvidenceEligibleEvent",
    "AlertEligibleEvent",
    "ObservedEvent",
    "InferredEvent",
    "PredictedEvent",
    "HypothesisEvent",
    "assemble_evidence",
    "raise_alert",
    "confirm_prediction",
    "event_v2_to_dict",
    "event_v2_from_dict",
    "RelationshipBasis",
    "RELATIONSHIP_BASES",
    "CorrectionKind",
    "CORRECTION_KINDS",
    "Relationship",
    "RelationshipError",
    "Correction",
    "DerivedArtifact",
    "ArtifactRegistry",
    "EvidenceError",
    "DerivationStep",
    "Evidence",
    "CommitmentStatus",
    "COMMITMENT_STATUSES",
    "compute_merkle_root",
    "EvidenceCommitment",
    "CalibrationRecord",
    "UncalibratedScore",
    "CalibratedProbability",
    "Confidence",
    "ParticipantRole",
    "PARTICIPANT_ROLES",
    "Participant",
    "Episode",
    "EpisodeError",
    "ActivityLabel",
    "ACTIVITY_LABELS",
    "ActivityScopeKind",
    "ACTIVITY_SCOPE_KINDS",
    "ActivityMode",
    "attach_to_alert",
    "attach_to_evidence",
    "Factor",
    "StateQuery",
    "StateGraph",
    "solve_state",
    "WorldPosition",
    "RigidTransform3D",
    "TwinRevTransform",
    "TwinRevTransformRegistry",
    "TwinRevError",
    "AlertEmissionEligibleEvent",
    "AlertError",
    "Alert",
    "emit_alert",
    "ExplainabilityError",
    "ExplainedHop",
    "ExplainedAlert",
    "explain",
]
