import pandas as pd
import numpy as np
import json
from pathlib import Path


def convert_csv_to_json(csv_path: str, output_json_path: str, fps: int = 30):
    try:
        # Load the CSV generated by projector_vectorized.py
        df = pd.read_csv(csv_path)
    except FileNotFoundError:
        print(
            f"ERROR: {csv_path} not found. "
            "Ensure you ran projector_vectorized.py first."
        )
        return

    # Task 9.2: Failsafe Semantic Coloring
    # Since we are using dummy data, we generate colors based on point_id
    df["r"] = df.groupby("point_id")["point_id"].transform(lambda x: np.random.rand())
    df["g"] = df.groupby("point_id")["point_id"].transform(lambda x: np.random.rand())
    df["b"] = df.groupby("point_id")["point_id"].transform(lambda x: np.random.rand())

    tracks_data = []
    # Map CSV columns (frame_id, X, Y, Z) to JSON format
    for track_id, group in df.groupby("point_id"):
        path = []
        for _, row in group.iterrows():
            path.append(
                {
                    "f": int(row["frame_id"]),
                    "x": float(row["X"]),
                    "y": float(row["Y"]),
                    "z": float(row["Z"]),
                    "r": float(row["r"]),
                    "g": float(row["g"]),
                    "b": float(row["b"]),
                }
            )
        path = sorted(path, key=lambda p: p["f"])
        tracks_data.append({"id": int(track_id), "path": path})

    final_data = {"fps": fps, "tracks": tracks_data}
    out_path = Path(output_json_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w") as f:
        json.dump(final_data, f)

    print(f"SUCCESS: Semantic trajectory data exported to {output_json_path}")


if __name__ == "__main__":
    # Point exactly to the file created in your last terminal output
    convert_csv_to_json(
        "outputs/point_cloud_tracks.csv", "src/interface/ui/trajectory_data.json"
    )
