"""Generate a synthetic indoor dataset with exact ground truth.

Why this renderer and not Kubric
--------------------------------
The data strategy names Kubric (Apache-2.0) as the lane-S generator. Kubric
renders through Blender, and Kubric 0.1.1 pins the Blender 2.93/3.x-era ``bpy``
API; the Blender available here is 4.5, which it does not support. The official
path is a multi-gigabyte Docker image.

Rather than pretend, this generates scenes analytically: rooms, furniture and
agents are geometric primitives with closed-form depth, so the ground truth is
*exact* rather than rendered-and-read-back. That is a genuine advantage for
depth and occlusion GT — there is no z-buffer quantisation and no anti-aliasing
ambiguity at object edges.

What it is not: photorealistic. There is no global illumination, no material
response, no lens model. A perception number measured here is a geometry and
motion number, not an appearance number, and the manifest says so. Real indoor
footage from Site Zero supersedes this for anything a customer sees.

The SMPL trap, avoided by construction
--------------------------------------
Several excellent synthetic-human datasets (BEDLAM, AGORA) are built on SMPL
body models, whose commercial use requires a separate Meshcapade license.
Synthetic does not mean free. Every asset here is generated from primitives by
this file — boxes, cylinders, planes — so there is no third-party asset in the
stack at all, and the per-asset clearance record in the registry says exactly
that rather than pointing at someone else's terms.

Agents are articulated primitives: a torso box, a head sphere and two swinging
leg cylinders. They are recognisably person-shaped and person-scaled, and they
are nobody's likeness.

    python scripts/gen_synthetic_indoor.py
    python scripts/gen_synthetic_indoor.py --scenes 4 --frames 48
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np

from src.config import IronConfig
from src.data.golden import Condition

DATASET_NAME = "synthetic-indoor-v1"
NANOSECONDS_PER_SECOND = 1_000_000_000

# Every asset in the generation stack, and where its rights come from. This is
# the per-asset clearance record the strategy document requires — and it is
# short precisely because nothing here was imported.
ASSET_CLEARANCE: list[dict[str, str]] = [
    {
        "asset": "room shell (floor, ceiling, four walls)",
        "origin": "axis-aligned planes generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
    {
        "asset": "furniture (desks, cabinets, partitions)",
        "origin": "axis-aligned boxes generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
    {
        "asset": "agents (torso box, head sphere, two leg cylinders)",
        "origin": "articulated primitives generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "NO — this is the SMPL trap, avoided by construction. "
        "No body model, no scan, no likeness of any person.",
    },
    {
        "asset": "textures",
        "origin": "seeded procedural noise generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
]


@dataclass(frozen=True)
class CameraSpec:
    """A pinhole camera with a known pose. Intrinsics are exact, not guessed."""

    name: str
    width: int
    height: int
    fx: float
    fy: float
    position: tuple[float, float, float]
    yaw_degrees: float
    covers: str

    @property
    def cx(self) -> float:
        return self.width / 2.0

    @property
    def cy(self) -> float:
        return self.height / 2.0

    def extrinsics(self) -> np.ndarray:
        """World->camera 4x4. Yaw about the vertical axis only."""
        yaw = np.radians(self.yaw_degrees)
        rotation = np.array(
            [
                [np.cos(yaw), 0.0, np.sin(yaw)],
                [0.0, 1.0, 0.0],
                [-np.sin(yaw), 0.0, np.cos(yaw)],
            ]
        )
        matrix = np.eye(4)
        matrix[:3, :3] = rotation
        matrix[:3, 3] = -rotation @ np.array(self.position)
        return matrix


@dataclass
class Agent:
    """A person-shaped articulated primitive walking a straight line."""

    agent_id: int
    start: tuple[float, float]
    end: tuple[float, float]
    height_m: float = 1.72
    speed_scale: float = 1.0

    def position_at(self, t: float) -> np.ndarray:
        """World position (x, y, z) at normalised time ``t`` in [0, 1]."""
        progress = min(1.0, t * self.speed_scale)
        x = self.start[0] + (self.end[0] - self.start[0]) * progress
        z = self.start[1] + (self.end[1] - self.start[1]) * progress
        return np.array([x, self.height_m / 2.0, z])


@dataclass
class Furniture:
    """An axis-aligned box: desk, cabinet or partition."""

    name: str
    centre: tuple[float, float, float]
    size: tuple[float, float, float]

    def occludes(self, point: np.ndarray, camera_pos: np.ndarray) -> bool:
        """Whether this box lies between the camera and ``point``.

        A slab test along the view ray. Analytic, so the occlusion flag is
        exact rather than inferred from a depth buffer.
        """
        direction = point - camera_pos
        distance = float(np.linalg.norm(direction))
        if distance < 1e-9:
            return False
        direction = direction / distance

        lo = np.array(self.centre) - np.array(self.size) / 2.0
        hi = np.array(self.centre) + np.array(self.size) / 2.0

        t_near, t_far = 0.0, distance
        for axis in range(3):
            if abs(direction[axis]) < 1e-9:
                if camera_pos[axis] < lo[axis] or camera_pos[axis] > hi[axis]:
                    return False
                continue
            t1 = (lo[axis] - camera_pos[axis]) / direction[axis]
            t2 = (hi[axis] - camera_pos[axis]) / direction[axis]
            t_near = max(t_near, min(t1, t2))
            t_far = min(t_far, max(t1, t2))
            if t_near > t_far:
                return False
        return t_near < distance


@dataclass
class Scene:
    """One synthetic indoor scene."""

    name: str
    room_size: tuple[float, float, float]
    cameras: list[CameraSpec]
    agents: list[Agent]
    furniture: list[Furniture]
    conditions: tuple[Condition, ...]
    frames: int
    fps: float
    notes: str = ""
    lights_off_from: int | None = None
    blown_window: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


def project(point: np.ndarray, camera: CameraSpec) -> tuple[float, float, float]:
    """World point -> (u, v, depth_metres). Standard pinhole, exact."""
    homogeneous = np.append(point, 1.0)
    in_camera = camera.extrinsics() @ homogeneous
    x, y, z = in_camera[:3]
    if z <= 1e-6:
        return (float("nan"), float("nan"), float(z))
    u = camera.fx * (x / z) + camera.cx
    v = camera.fy * (-y / z) + camera.cy
    return (float(u), float(v), float(z))


def render_frame(
    scene: Scene, camera: CameraSpec, frame: int, texture: np.ndarray
) -> dict[str, np.ndarray]:
    """Render one frame plus its exact ground truth.

    Returns rgb, depth (metres), instance segmentation. Depth is computed
    analytically per pixel for the room shell and per object for agents and
    furniture, so it carries no z-buffer quantisation.
    """
    height, width = camera.height, camera.width
    t = frame / max(1, scene.frames - 1)

    # Room shell: depth to the back wall, shaded by a procedural texture.
    room_w, room_h, room_d = scene.room_size
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float64)
    ray_x = (xx - camera.cx) / camera.fx
    ray_y = -(yy - camera.cy) / camera.fy
    # Distance to the far wall along each ray (the wall is at z = room_d).
    depth = np.full((height, width), room_d, dtype=np.float64)
    depth = depth * np.sqrt(1.0 + ray_x**2 + ray_y**2)

    base = 110 + 25 * np.sin(xx / 47.0) + 18 * np.cos(yy / 61.0) + texture
    rgb = np.clip(np.stack([base, base * 0.97, base * 0.93], axis=2), 0, 255)

    instances = np.zeros((height, width), dtype=np.int32)

    # Furniture: filled boxes, nearer than the wall.
    for index, item in enumerate(scene.furniture, start=1):
        u, v, z = project(np.array(item.centre), camera)
        if not np.isfinite(u):
            continue
        half_u = camera.fx * (item.size[0] / 2.0) / max(z, 1e-6)
        half_v = camera.fy * (item.size[1] / 2.0) / max(z, 1e-6)
        u0, u1 = int(u - half_u), int(u + half_u)
        v0, v1 = int(v - half_v), int(v + half_v)
        u0, u1 = max(0, u0), min(width, u1)
        v0, v1 = max(0, v0), min(height, v1)
        if u0 >= u1 or v0 >= v1:
            continue
        nearer = z < depth[v0:v1, u0:u1]
        region = rgb[v0:v1, u0:u1]
        region[nearer] = np.array([88.0, 76.0, 64.0])
        depth[v0:v1, u0:u1][nearer] = z
        instances[v0:v1, u0:u1][nearer] = index

    # Agents: torso + head + legs, drawn nearest-first via the depth test.
    for agent in scene.agents:
        centre = agent.position_at(t)
        u, v, z = project(centre, camera)
        if not np.isfinite(u):
            continue
        torso_h = camera.fy * (agent.height_m * 0.45) / max(z, 1e-6)
        torso_w = camera.fx * 0.34 / max(z, 1e-6)
        head_r = camera.fy * 0.11 / max(z, 1e-6)

        # Legs swing with a gait phase, so motion is articulated rather than a
        # rigid box sliding — which matters for anything measuring motion.
        phase = np.sin(2 * np.pi * (t * 4.0 + agent.agent_id))
        for part_u, part_v, part_hu, part_hv in (
            (u, v, torso_w / 2, torso_h / 2),
            (u, v - torso_h / 2 - head_r, head_r, head_r),
            (
                u - torso_w / 4 + phase * torso_w / 6,
                v + torso_h / 2 + torso_h / 4,
                torso_w / 8,
                torso_h / 4,
            ),
            (
                u + torso_w / 4 - phase * torso_w / 6,
                v + torso_h / 2 + torso_h / 4,
                torso_w / 8,
                torso_h / 4,
            ),
        ):
            u0, u1 = int(part_u - part_hu), int(part_u + part_hu)
            v0, v1 = int(part_v - part_hv), int(part_v + part_hv)
            u0, u1 = max(0, u0), min(width, u1)
            v0, v1 = max(0, v0), min(height, v1)
            if u0 >= u1 or v0 >= v1:
                continue
            nearer = z < depth[v0:v1, u0:u1]
            rgb[v0:v1, u0:u1][nearer] = np.array([180.0, 150.0, 130.0])
            depth[v0:v1, u0:u1][nearer] = z
            instances[v0:v1, u0:u1][nearer] = 100 + agent.agent_id

    # Degenerates.
    if scene.lights_off_from is not None and frame >= scene.lights_off_from:
        rgb *= 0.12
    if scene.blown_window:
        rgb[: height // 3, -width // 4 :] = 255.0

    return {
        "rgb": np.clip(rgb, 0, 255).astype(np.uint8),
        "depth_m": depth.astype(np.float32),
        "instances": instances,
    }


def build_scenes(frames: int, fps: float) -> list[Scene]:
    """The scene set: coverage, overlap, a gap, and degenerates."""
    room = (8.0, 3.0, 12.0)

    # A camera pair with genuine overlap, plus a third with a deliberate
    # coverage gap between it and the pair. Both are things annotation cannot
    # add later: cross-camera association GT needs the overlap, and blind-spot
    # handoff eval needs the gap.
    cam_a_720 = CameraSpec(
        "cam_a",
        1280,
        720,
        900.0,
        900.0,
        (-2.0, 2.6, 0.0),
        15.0,
        "left half, overlaps cam_b",
    )
    cam_b_720 = CameraSpec(
        "cam_b",
        1280,
        720,
        900.0,
        900.0,
        (2.0, 2.6, 0.0),
        -15.0,
        "right half, overlaps cam_a",
    )
    cam_c_720 = CameraSpec(
        "cam_c",
        1280,
        720,
        900.0,
        900.0,
        (0.0, 2.6, 11.0),
        180.0,
        "far end; a coverage GAP separates it from the pair",
    )
    cam_a_1080 = CameraSpec(
        "cam_a_1080",
        1920,
        1080,
        1350.0,
        1350.0,
        (-2.0, 2.6, 0.0),
        15.0,
        "1080p rendition of cam_a",
    )

    desks = [
        Furniture("desk_1", (-1.5, 0.4, 4.0), (1.6, 0.8, 0.8)),
        Furniture("desk_2", (1.8, 0.4, 5.5), (1.6, 0.8, 0.8)),
        Furniture("partition", (0.0, 0.9, 7.0), (2.4, 1.8, 0.15)),
    ]

    def walkers(count: int) -> list[Agent]:
        return [
            Agent(i, (-3.0 + 1.4 * i, 2.0), (3.0 - 1.0 * i, 9.5), speed_scale=1.0)
            for i in range(count)
        ]

    return [
        Scene(
            "overlap_pair_2agents",
            room,
            [cam_a_720, cam_b_720],
            walkers(2),
            desks,
            (
                Condition.DAYLIGHT,
                Condition.SINGLE_PERSON,
                Condition.OCCLUSION_FURNITURE,
            ),
            frames,
            fps,
            "camera pair with overlap; 2 agents behind desks",
        ),
        Scene(
            "coverage_gap_3agents",
            room,
            [cam_a_720, cam_c_720],
            walkers(3),
            desks,
            (
                Condition.DAYLIGHT,
                Condition.BLIND_SPOT_TRAVERSAL,
                Condition.OCCLUSION_CROSSING,
            ),
            frames,
            fps,
            "deliberate coverage gap between cam_a and cam_c",
        ),
        Scene(
            "crowded_6agents",
            room,
            [cam_a_720],
            walkers(6),
            desks,
            (Condition.DAYLIGHT, Condition.CROWDED, Condition.OCCLUSION_CROSSING),
            frames,
            fps,
            "6 agents, heavy mutual occlusion",
        ),
        Scene(
            "far_field_1080p",
            room,
            [cam_a_1080],
            walkers(2),
            desks,
            (Condition.DAYLIGHT, Condition.FAR_FIELD),
            frames,
            fps,
            "1080p rendition; agents at the far end of the envelope",
        ),
        Scene(
            "lights_off_transient",
            room,
            [cam_a_720],
            walkers(2),
            desks,
            (Condition.LIGHTS_TRANSIENT, Condition.EVENING_ARTIFICIAL),
            frames,
            fps,
            "lights cut mid-clip",
            lights_off_from=frames // 2,
        ),
        Scene(
            "blown_window",
            room,
            [cam_a_720],
            walkers(2),
            desks,
            (Condition.GLARE, Condition.DAYLIGHT),
            frames,
            fps,
            "blown-out window in frame",
            blown_window=True,
        ),
        Scene(
            "near_static",
            room,
            [cam_a_720],
            [Agent(0, (0.0, 6.0), (0.05, 6.0), speed_scale=1.0)],
            desks,
            (Condition.EMPTY, Condition.DAYLIGHT),
            frames,
            fps,
            "near-static: one agent barely moving",
        ),
    ]


def sha256_array(array: np.ndarray) -> str:
    digest = hashlib.sha256()
    digest.update(str(array.shape).encode())
    digest.update(str(array.dtype).encode())
    digest.update(np.ascontiguousarray(array).tobytes())
    return digest.hexdigest()


def generate(output_root: Path, frames: int, fps: float, seed: int) -> dict[str, Any]:
    """Render every scene and write clips plus exact GT."""
    scenes = build_scenes(frames, fps)
    output_root.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    for scene in scenes:
        for camera in scene.cameras:
            clip_id = f"{scene.name}__{camera.name}"
            # Python's hash() is salted per process (PYTHONHASHSEED), so using
            # it here made content_sha irreproducible across runs — which
            # defeats the entire point of a content-addressed golden set.
            # blake2s is stable everywhere.
            stream = int.from_bytes(
                hashlib.blake2s(clip_id.encode(), digest_size=4).digest(), "big"
            )
            rng = np.random.default_rng(seed + stream % 10_000)

            # Surface texture belongs to the wall, not to the moment. Drawing
            # it inside the frame loop resampled it every frame, which put
            # sigma=3 grain on 83% of pixels of a static scene and silently
            # turned "surface texture" into undeclared sensor noise that the
            # motion gate was then scored against.
            texture = rng.normal(0.0, 3.0, size=(camera.height, camera.width))

            rgb_stack, depth_stack, inst_stack = [], [], []
            agent_xyz, track_uv, track_occ = [], [], []

            for frame in range(scene.frames):
                out = render_frame(scene, camera, frame, texture)
                rgb_stack.append(out["rgb"])
                depth_stack.append(out["depth_m"])
                inst_stack.append(out["instances"])

                t = frame / max(1, scene.frames - 1)
                positions, uvs, occluded = [], [], []
                for agent in scene.agents:
                    world = agent.position_at(t)
                    u, v, _z = project(world, camera)
                    positions.append(world)
                    uvs.append([u, v])
                    hidden = any(
                        f.occludes(world, np.array(camera.position))
                        for f in scene.furniture
                    )
                    off_frame = not (
                        0 <= u < camera.width and 0 <= v < camera.height
                    ) or not np.isfinite(u)
                    occluded.append(bool(hidden or off_frame))
                agent_xyz.append(positions)
                track_uv.append(uvs)
                track_occ.append(occluded)

            clip_path = output_root / f"{clip_id}.npz"
            payload = {
                "rgb": np.stack(rgb_stack),
                "depth_m": np.stack(depth_stack),
                "instances": np.stack(inst_stack),
                "agent_xyz": np.asarray(agent_xyz, dtype=np.float32),
                "track_uv": np.asarray(track_uv, dtype=np.float32),
                "track_occluded": np.asarray(track_occ, dtype=bool),
                "intrinsics": np.array(
                    [camera.fx, camera.fy, camera.cx, camera.cy], dtype=np.float64
                ),
                "extrinsics": camera.extrinsics(),
            }
            np.savez_compressed(clip_path, **payload)

            records.append(
                {
                    "clip_id": clip_id,
                    "scene": scene.name,
                    "camera": camera.name,
                    "covers": camera.covers,
                    "resolution": [camera.width, camera.height],
                    "frames": scene.frames,
                    "fps": fps,
                    "agents": len(scene.agents),
                    "conditions": [c.value for c in scene.conditions],
                    "notes": scene.notes,
                    "content_sha": sha256_array(payload["rgb"]),
                    "depth_sha": sha256_array(payload["depth_m"]),
                    "moving_frames": int(scene.frames),
                    "size_bytes": clip_path.stat().st_size,
                }
            )
            print(
                f"  {clip_id:34} {camera.width}x{camera.height} "
                f"{scene.frames}f  {clip_path.stat().st_size/1e6:5.1f} MB"
            )

    manifest = {
        "schema_version": "1.0",
        "dataset": DATASET_NAME,
        "lane": "S",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/gen_synthetic_indoor.py",
        "seed": seed,
        "renderer": {
            "kind": "analytic primitives (not Kubric, not photorealistic)",
            "why_not_kubric": (
                "Kubric 0.1.1 pins the Blender 2.93/3.x-era bpy API; the "
                "available Blender is 4.5, and the official path is a "
                "multi-gigabyte Docker image. Analytic primitives give EXACT "
                "closed-form depth and occlusion instead of rendered-and-read-"
                "back GT, which is a real advantage for geometry — at the cost "
                "of any appearance realism."
            ),
            "limitations": (
                "No global illumination, no material response, no lens model, "
                "and NO sensor noise at all: surface texture is fixed per "
                "camera, so a static scene produces bit-identical frames. A "
                "motion-gate score here therefore measures the gate against "
                "clean input and is an UPPER BOUND on real-camera precision. "
                "A number measured here is a GEOMETRY and MOTION number, not "
                "an appearance one."
            ),
        },
        "asset_clearance": ASSET_CLEARANCE,
        "supersession": (
            "SYNTHETIC-ONLY BASELINE. Real indoor footage from Site Zero "
            "supersedes this for every product claim. A scorecard computed "
            "against this dataset MUST NOT be quoted externally."
        ),
        "ground_truth": [
            "depth_m: per-pixel metric depth, analytic",
            "agent_xyz: per-frame 3D agent positions, metres",
            "track_uv: per-frame projected agent pixel coordinates",
            "track_occluded: per-frame occlusion flag, analytic slab test",
            "instances: per-pixel instance segmentation",
            "intrinsics / extrinsics: exact, not estimated",
        ],
        "clips": records,
    }
    (output_root / "dataset_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return manifest


def write_golden_from_manifest(
    manifest: dict[str, Any], version: str, config: Any
) -> Path:
    """Mint a golden set from a freshly generated manifest.

    The content hashes in a golden set are its whole value, so they must come
    from the generator that produced the bytes rather than from a person
    pasting them. Overwrite is permitted here only because a synthetic set is
    regenerable by definition; a set containing captured footage is immutable
    and must go through ``GoldenSet.with_clips`` under a new version.
    """
    from src.data.golden import (
        Condition,
        Domain,
        GoldenClip,
        GoldenSet,
        Status,
        write_golden_set,
    )

    clips = tuple(
        GoldenClip(
            clip_id=record["clip_id"],
            content_sha=record["content_sha"],
            conditions=tuple(Condition(c) for c in record["conditions"]),
            source_dataset=DATASET_NAME,
            notes=f"{record['camera']} {record['resolution'][0]}x"
            f"{record['resolution'][1]}, {record['agents']} agents — "
            f"{record['covers']}",
        )
        for record in manifest["clips"]
    )
    golden = GoldenSet(
        version=version,
        domain=Domain.INDOOR,
        status=Status.ACTIVE,
        clips=clips,
        supersedes="v1-driving",
        description=(
            "SYNTHETIC-ONLY. Generated by scripts/gen_synthetic_indoor.py "
            "--write-golden. Superseded by Site Zero footage for any product "
            "claim; scores from it must not be quoted externally."
        ),
    )
    return write_golden_set(
        config.paths.project_root / "configs" / "golden", golden, True
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frames", type=int, default=24)
    parser.add_argument("--fps", type=float, default=12.0)
    parser.add_argument("--seed", type=int, default=20260801)
    parser.add_argument("--output", default=None)
    parser.add_argument(
        "--write-golden",
        metavar="VERSION",
        default=None,
        help=(
            "Mint a golden set of this version from the manifest. Without "
            "this the golden set can only be built by hand, and a hand-built "
            "set of content hashes is one that nobody can reproduce."
        ),
    )
    args = parser.parse_args(argv)

    config = IronConfig.load()
    output = (
        Path(args.output)
        if args.output
        else config.paths.resolved_data_dir / "synthetic" / DATASET_NAME
    )

    print(f"Generating {DATASET_NAME} -> {output}")
    print("Renderer: analytic primitives (see manifest for why not Kubric)\n")
    manifest = generate(output, args.frames, args.fps, args.seed)

    print(f"\n{len(manifest['clips'])} clips written.")
    print(f"Manifest: {output / 'dataset_manifest.json'}")

    if args.write_golden:
        path = write_golden_from_manifest(manifest, args.write_golden, config)
        print(f"Golden set {args.write_golden}: {path}")
    print(
        "\nSYNTHETIC-ONLY BASELINE. Real Site Zero footage supersedes this for "
        "product claims;\na scorecard from it must not be quoted externally."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
