"""Generate a synthetic indoor dataset with exact ground truth.

Why this renderer and not Kubric
--------------------------------
The data strategy names Kubric (Apache-2.0) as the lane-S generator. Kubric
renders through Blender, and Kubric 0.1.1 pins the Blender 2.93/3.x-era ``bpy``
API; the Blender available here is 4.5, which it does not support. The official
path is a multi-gigabyte Docker image.

Rather than pretend, this generates scenes analytically: rooms, furniture and
agents are geometric primitives with closed-form depth, so the ground truth is
*exact* rather than rendered-and-read-back. That is a genuine advantage for
depth and occlusion GT — there is no z-buffer quantisation and no anti-aliasing
ambiguity at object edges.

What it is not: photorealistic. There is no global illumination, no material
response, no lens model. A perception number measured here is a geometry and
motion number, not an appearance number, and the manifest says so. Real indoor
footage from Site Zero supersedes this for anything a customer sees.

The SMPL trap, avoided by construction
--------------------------------------
Several excellent synthetic-human datasets (BEDLAM, AGORA) are built on SMPL
body models, whose commercial use requires a separate Meshcapade license.
Synthetic does not mean free. Every asset here is generated from primitives by
this file — boxes, cylinders, planes — so there is no third-party asset in the
stack at all, and the per-asset clearance record in the registry says exactly
that rather than pointing at someone else's terms.

Agents are articulated primitives: a torso box, a head sphere and two swinging
leg cylinders. They are recognisably person-shaped and person-scaled, and they
are nobody's likeness.

    python scripts/gen_synthetic_indoor.py
    python scripts/gen_synthetic_indoor.py --scenes 4 --frames 48
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np

from src.config import IronConfig
from src.data.golden import Condition

DATASET_NAME = "synthetic-indoor-v1"

DATASET_NAMES = {
    "v2": "synthetic-indoor-v1",
    "v3": "synthetic-indoor-v3",
    "v4-gate": "synthetic-indoor-v4-gate",
    "v4.1-gate": "synthetic-indoor-v4.1-gate",
    "v5-cessation": "synthetic-indoor-v5-cessation",
}
"""Scene set -> dataset directory and registry name.

Separate directories because the sets are separate instruments. v2's bytes are
cited by a frozen manifest, so rendering v3 over the top of them would leave
the v2 golden set pointing at clips that no longer hash to what it records.
v4-gate (Day 16) is a distinct instrument for a different reason: it exists
to measure a motion gate, not tracking or depth, and its scenes are authored
quiet on purpose — mixing them into v3's directory would put low-activity
clips under a dataset name whose own manifest says its agents were authored
to move. v4.1-gate (Day 17) is v4-gate's scenes, unchanged, re-rendered
under the gait-phase fix (see build_scenes_v4_gate and Agent.progress_at).
v4-gate itself is NEVER edited or overwritten — it remains the record of
what "authored quiet" measured before the fix existed, exactly as v1
stayed the record after v2 superseded it.
to move. v5-cessation (Day 23) is a third distinct instrument again: it
exists to supply CESSATION VOLUME specifically (see build_scenes_v5_cessation)
-- it never touches v3's or v4.1-gate's directories or clips."""
NANOSECONDS_PER_SECOND = 1_000_000_000

# Every asset in the generation stack, and where its rights come from. This is
# the per-asset clearance record the strategy document requires — and it is
# short precisely because nothing here was imported.
ASSET_CLEARANCE: list[dict[str, str]] = [
    {
        "asset": "room shell (floor, ceiling, four walls)",
        "origin": "axis-aligned planes generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
    {
        "asset": "furniture (desks, cabinets, partitions)",
        "origin": "axis-aligned boxes generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
    {
        "asset": "agents (torso box, head sphere, two leg cylinders)",
        "origin": "articulated primitives generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "NO — this is the SMPL trap, avoided by construction. "
        "No body model, no scan, no likeness of any person.",
    },
    {
        "asset": "textures",
        "origin": "seeded procedural noise generated by this file",
        "license": "ours — no third-party asset",
        "smpl_derived": "no",
    },
]


@dataclass(frozen=True)
class CameraSpec:
    """A pinhole camera with a known pose. Intrinsics are exact, not guessed."""

    name: str
    width: int
    height: int
    fx: float
    fy: float
    position: tuple[float, float, float]
    yaw_degrees: float
    covers: str
    pitch_degrees: float = 0.0
    """Downward tilt. Positive points the camera at the floor.

    Defaults to zero so that v2-indoor, authored before this existed, still
    renders byte-identically — its content hashes are cited by a frozen
    manifest.

    v2 had no pitch, which is why its agents walked off the bottom edge: a
    camera 2.6 m up looking dead level puts a 1.7 m person below the principal
    point, and further below it the closer they get. A real mounted camera
    tilts down; without that the set was measuring a mount nobody would build.
    """

    @property
    def cx(self) -> float:
        return self.width / 2.0

    @property
    def cy(self) -> float:
        return self.height / 2.0

    def extrinsics(self) -> np.ndarray:
        """World->camera 4x4. Yaw about the vertical axis, then pitch down."""
        yaw = np.radians(self.yaw_degrees)
        rotation = np.array(
            [
                [np.cos(yaw), 0.0, np.sin(yaw)],
                [0.0, 1.0, 0.0],
                [-np.sin(yaw), 0.0, np.cos(yaw)],
            ]
        )
        if self.pitch_degrees:
            pitch = np.radians(self.pitch_degrees)
            tilt = np.array(
                [
                    [1.0, 0.0, 0.0],
                    [0.0, np.cos(pitch), np.sin(pitch)],
                    [0.0, -np.sin(pitch), np.cos(pitch)],
                ]
            )
            rotation = tilt @ rotation
        matrix = np.eye(4)
        matrix[:3, :3] = rotation
        matrix[:3, 3] = -rotation @ np.array(self.position)
        return matrix


@dataclass
class Agent:
    """A person-shaped articulated primitive walking a straight line."""

    agent_id: int
    start: tuple[float, float]
    end: tuple[float, float]
    height_m: float = 1.72
    speed_scale: float = 1.0

    def progress_at(self, t: float) -> float:
        """Fraction of the start->end path covered by normalised time ``t``.

        Clamped at 1.0: an agent that reaches ``end`` stays there, the same
        convention :meth:`position_at` uses. Distance travelled is
        ``progress_at(t) * path length``, a linear function of this value —
        anything that should advance with MOTION rather than with wall-clock
        time (Day 17: gait phase) drives off this, not off ``t`` directly.
        """
        return min(1.0, t * self.speed_scale)

    def position_at(self, t: float) -> np.ndarray:
        """World position (x, y, z) at normalised time ``t`` in [0, 1]."""
        progress = self.progress_at(t)
        x = self.start[0] + (self.end[0] - self.start[0]) * progress
        z = self.start[1] + (self.end[1] - self.start[1]) * progress
        return np.array([x, self.height_m / 2.0, z])


@dataclass
class PathSegment:
    """One leg of a :class:`MultiSegmentAgent`'s piecewise-linear path
    (Day 23, v5-cessation).

    Attributes:
        end: World (x, z) this leg walks to.
        duration: This leg's share of the agent's total normalised time
            ``[0, 1]`` — NOT seconds; :func:`_seconds_to_path_fractions`
            converts a scene's second-denominated timeline into these
            fractions before construction, the same way ``fps``/``frames``
            already convert seconds to frame counts elsewhere in this file.
        ease_out: ``False`` (default) — constant velocity for the whole
            leg, then an INSTANTANEOUS stop at ``end`` (an abrupt halt).
            ``True`` — velocity ramps smoothly to zero over the last
            ``ease_fraction`` of the leg (a gradual deceleration). A
            zero-length leg (``end`` equal to the previous waypoint) is a
            PAUSE: position does not change for its whole ``duration``
            regardless of this flag, which is exactly how stop-duration
            and stop-then-restart sequences are built — see
            :func:`build_scenes_v5_cessation`.
        ease_fraction: Fraction of THIS leg's own duration over which
            ``ease_out`` ramps speed to zero. Unused when ``ease_out`` is
            ``False``.
    """

    end: tuple[float, float]
    duration: float
    ease_out: bool = False
    ease_fraction: float = 0.3


@dataclass
class MultiSegmentAgent:
    """A person-shaped articulated primitive walking a PIECEWISE-linear
    path — several straight legs, each with its own duration and speed
    profile (Day 23, v5-cessation only).

    :class:`Agent` (single start->end leg, used by every existing scene
    set) is untouched by this class's existence — v3/v4-gate/v4.1-gate's
    builders never construct one. Duck-typed to the same public interface
    :func:`render_frame` and :func:`generate` already call polymorphically
    (``agent_id``, ``height_m``, ``position_at``, ``progress_at``), so
    v5-cessation's scenes can mix into the same ``Scene.agents`` list and
    rendering pipeline with no change to either.
    """

    agent_id: int
    start: tuple[float, float]
    segments: list[PathSegment]
    height_m: float = 1.72

    def __post_init__(self) -> None:
        if not self.segments:
            raise ValueError("MultiSegmentAgent needs at least one segment")
        if sum(s.duration for s in self.segments) <= 0:
            raise ValueError("segment durations must sum to a positive value")

    def _waypoints(self) -> list[tuple[float, float]]:
        return [self.start] + [s.end for s in self.segments]

    def _segment_lengths(self) -> list[float]:
        wp = self._waypoints()
        return [
            float(np.hypot(wp[i + 1][0] - wp[i][0], wp[i + 1][1] - wp[i][1]))
            for i in range(len(self.segments))
        ]

    def _cumulative_duration_fractions(self) -> list[float]:
        total = sum(s.duration for s in self.segments)
        cumulative = [0.0]
        for segment in self.segments:
            cumulative.append(cumulative[-1] + segment.duration / total)
        return cumulative

    def _locate(self, t: float) -> tuple[int, float]:
        """Which segment ``t`` (normalised full-path time in ``[0, 1]``)
        falls in, and the local (eased) progress within it."""
        cumulative = self._cumulative_duration_fractions()
        t = min(max(t, 0.0), 1.0)
        index = 0
        for i in range(len(self.segments)):
            if t >= cumulative[i]:
                index = i
        segment = self.segments[index]
        span = cumulative[index + 1] - cumulative[index]
        local_t = 1.0 if span <= 0 else min(1.0, (t - cumulative[index]) / span)
        if segment.ease_out and local_t > (1.0 - segment.ease_fraction):
            # Ease-out quadratic over the tail fraction: velocity ramps to
            # zero smoothly instead of stopping the instant `end` is reached.
            tail_start = 1.0 - segment.ease_fraction
            tail_t = (local_t - tail_start) / segment.ease_fraction
            eased_tail = 1.0 - (1.0 - tail_t) ** 2
            local_t = tail_start + eased_tail * segment.ease_fraction
        return index, local_t

    def position_at(self, t: float) -> np.ndarray:
        index, local_t = self._locate(t)
        waypoints = self._waypoints()
        p0, p1 = waypoints[index], waypoints[index + 1]
        x = p0[0] + (p1[0] - p0[0]) * local_t
        z = p0[1] + (p1[1] - p0[1]) * local_t
        return np.array([x, self.height_m / 2.0, z])

    def progress_at(self, t: float) -> float:
        """Cumulative DISTANCE-based progress (not time-based) along the
        whole path, in ``[0, 1]``.

        Gait phase drives off this (see :func:`render_frame`), so it must
        hold exactly flat whenever position is not changing — a pause leg,
        or the eased tail of a decelerating one once it has effectively
        stopped. A zero-length (pause) leg contributes zero to the
        cumulative distance regardless of ``local_t``, which is what makes
        that invariant hold for free rather than needing special-cased
        pause handling — the same Day-17 principle
        :meth:`Agent.progress_at` established, generalised to a
        multi-leg path.
        """
        index, local_t = self._locate(t)
        lengths = self._segment_lengths()
        total_length = sum(lengths)
        if total_length <= 0:
            return 0.0
        traveled = sum(lengths[:index]) + lengths[index] * local_t
        return traveled / total_length


def _seconds_to_path_fractions(seconds: list[float]) -> list[float]:
    """Convert a list of leg durations in SECONDS to the normalised
    ``duration`` fractions :class:`PathSegment` expects (summing to 1.0
    over the whole path) — lets :func:`build_scenes_v5_cessation` author
    walk/stop timing in seconds, the units its own parameters (approach
    speed, stop duration) are naturally stated in."""
    total = sum(seconds)
    if total <= 0:
        raise ValueError("segment seconds must sum to a positive value")
    return [s / total for s in seconds]


@dataclass
class Furniture:
    """An axis-aligned box: desk, cabinet or partition."""

    name: str
    centre: tuple[float, float, float]
    size: tuple[float, float, float]

    def occludes(self, point: np.ndarray, camera_pos: np.ndarray) -> bool:
        """Whether this box lies between the camera and ``point``.

        A slab test along the view ray. Analytic, so the occlusion flag is
        exact rather than inferred from a depth buffer.
        """
        direction = point - camera_pos
        distance = float(np.linalg.norm(direction))
        if distance < 1e-9:
            return False
        direction = direction / distance

        lo = np.array(self.centre) - np.array(self.size) / 2.0
        hi = np.array(self.centre) + np.array(self.size) / 2.0

        t_near, t_far = 0.0, distance
        for axis in range(3):
            if abs(direction[axis]) < 1e-9:
                if camera_pos[axis] < lo[axis] or camera_pos[axis] > hi[axis]:
                    return False
                continue
            t1 = (lo[axis] - camera_pos[axis]) / direction[axis]
            t2 = (hi[axis] - camera_pos[axis]) / direction[axis]
            t_near = max(t_near, min(t1, t2))
            t_far = min(t_far, max(t1, t2))
            if t_near > t_far:
                return False
        return t_near < distance


@dataclass
class Scene:
    """One synthetic indoor scene."""

    name: str
    room_size: tuple[float, float, float]
    cameras: list[CameraSpec]
    agents: list[Agent | MultiSegmentAgent]
    furniture: list[Furniture]
    conditions: tuple[Condition, ...]
    frames: int
    fps: float
    notes: str = ""
    lights_off_from: int | None = None
    blown_window: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


def project(point: np.ndarray, camera: CameraSpec) -> tuple[float, float, float]:
    """World point -> (u, v, depth_metres). Standard pinhole, exact."""
    homogeneous = np.append(point, 1.0)
    in_camera = camera.extrinsics() @ homogeneous
    x, y, z = in_camera[:3]
    if z <= 1e-6:
        return (float("nan"), float("nan"), float(z))
    u = camera.fx * (x / z) + camera.cx
    v = camera.fy * (-y / z) + camera.cy
    return (float(u), float(v), float(z))


def render_frame(
    scene: Scene, camera: CameraSpec, frame: int, texture: np.ndarray
) -> dict[str, np.ndarray]:
    """Render one frame plus its exact ground truth.

    Returns rgb, depth (metres), instance segmentation. Depth is computed
    analytically per pixel for the room shell and per object for agents and
    furniture, so it carries no z-buffer quantisation.
    """
    height, width = camera.height, camera.width
    t = frame / max(1, scene.frames - 1)

    # Room shell: depth to the back wall, shaded by a procedural texture.
    room_w, room_h, room_d = scene.room_size
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float64)
    ray_x = (xx - camera.cx) / camera.fx
    ray_y = -(yy - camera.cy) / camera.fy
    # Distance to the far wall along each ray (the wall is at z = room_d).
    depth = np.full((height, width), room_d, dtype=np.float64)
    depth = depth * np.sqrt(1.0 + ray_x**2 + ray_y**2)

    base = 110 + 25 * np.sin(xx / 47.0) + 18 * np.cos(yy / 61.0) + texture
    rgb = np.clip(np.stack([base, base * 0.97, base * 0.93], axis=2), 0, 255)

    instances = np.zeros((height, width), dtype=np.int32)

    # Furniture: filled boxes, nearer than the wall.
    for index, item in enumerate(scene.furniture, start=1):
        u, v, z = project(np.array(item.centre), camera)
        if not np.isfinite(u):
            continue
        half_u = camera.fx * (item.size[0] / 2.0) / max(z, 1e-6)
        half_v = camera.fy * (item.size[1] / 2.0) / max(z, 1e-6)
        u0, u1 = int(u - half_u), int(u + half_u)
        v0, v1 = int(v - half_v), int(v + half_v)
        u0, u1 = max(0, u0), min(width, u1)
        v0, v1 = max(0, v0), min(height, v1)
        if u0 >= u1 or v0 >= v1:
            continue
        nearer = z < depth[v0:v1, u0:u1]
        region = rgb[v0:v1, u0:u1]
        region[nearer] = np.array([88.0, 76.0, 64.0])
        depth[v0:v1, u0:u1][nearer] = z
        instances[v0:v1, u0:u1][nearer] = index

    # Agents: torso + head + legs, drawn nearest-first via the depth test.
    for agent in scene.agents:
        centre = agent.position_at(t)
        u, v, z = project(centre, camera)
        if not np.isfinite(u):
            continue
        torso_h = camera.fy * (agent.height_m * 0.45) / max(z, 1e-6)
        torso_w = camera.fx * 0.34 / max(z, 1e-6)
        head_r = camera.fy * 0.11 / max(z, 1e-6)

        # Legs swing with a gait phase, so motion is articulated rather than a
        # rigid box sliding — which matters for anything measuring motion.
        #
        # Day 17: was `np.sin(2*pi*(t*4.0 + agent_id))` -- driven by ELAPSED
        # TIME, not by whether the agent was going anywhere. A speed_scale=0.0
        # agent has t advancing every frame while never moving, so its legs
        # swung through a full gait cycle every quarter-clip regardless: the
        # one clip v4-gate authored to be motionless (long_static_occupant)
        # rendered a silhouette that changed on ~92% of its frames, and
        # gt_moved_from_render (Day 9's silhouette-diff ground truth) scored
        # it as in near-constant motion. Driven by `progress_at(t)` instead --
        # the same [0, 1] path-completion fraction position_at(t) already
        # uses, clamped once the agent arrives -- so gait phase is a function
        # of DISTANCE TRAVELLED along the path. A stationary agent
        # (speed_scale=0.0) has progress_at(t) == 0.0 for every t, so phase is
        # the same constant every frame and the silhouette stops changing; an
        # agent that arrives and stops (progress_at(t) saturates at 1.0) stops
        # swinging its legs the moment it stops walking, the same as a real
        # person would.
        phase = np.sin(2 * np.pi * (agent.progress_at(t) * 4.0 + agent.agent_id))
        for part_u, part_v, part_hu, part_hv in (
            (u, v, torso_w / 2, torso_h / 2),
            (u, v - torso_h / 2 - head_r, head_r, head_r),
            (
                u - torso_w / 4 + phase * torso_w / 6,
                v + torso_h / 2 + torso_h / 4,
                torso_w / 8,
                torso_h / 4,
            ),
            (
                u + torso_w / 4 - phase * torso_w / 6,
                v + torso_h / 2 + torso_h / 4,
                torso_w / 8,
                torso_h / 4,
            ),
        ):
            u0, u1 = int(part_u - part_hu), int(part_u + part_hu)
            v0, v1 = int(part_v - part_hv), int(part_v + part_hv)
            u0, u1 = max(0, u0), min(width, u1)
            v0, v1 = max(0, v0), min(height, v1)
            if u0 >= u1 or v0 >= v1:
                continue
            nearer = z < depth[v0:v1, u0:u1]
            rgb[v0:v1, u0:u1][nearer] = np.array([180.0, 150.0, 130.0])
            depth[v0:v1, u0:u1][nearer] = z
            instances[v0:v1, u0:u1][nearer] = 100 + agent.agent_id

    # Degenerates.
    if scene.lights_off_from is not None and frame >= scene.lights_off_from:
        rgb *= 0.12
    if scene.blown_window:
        rgb[: height // 3, -width // 4 :] = 255.0

    return {
        "rgb": np.clip(rgb, 0, 255).astype(np.uint8),
        "depth_m": depth.astype(np.float32),
        "instances": instances,
    }


def build_scenes_v3(frames: int, fps: float) -> list[Scene]:
    """The v3 scene set: authored so its ground truth is actually observable.

    v2 scored ``observable_fraction`` 0.4444 for two traced reasons, both fixed
    here rather than tuned around.

    **Agents walked off the bottom edge.** Its cameras sat 2.6 m up with
    yaw-only extrinsics, so a 1.72 m agent fell further below the principal
    point the closer it came, and left the frame entirely from about 2 m. Every
    camera here is pitched down, and every path is kept inside a 3.5-11 m depth
    band. At 16 degrees of tilt an agent at 6 m lands on the principal point and
    one at 3 m still has its feet in frame.

    **A partition slab sat on the primary sightline.** ``partition`` at z=7.0
    spanned 2.4 m across the middle of the room, so the far camera watched
    agents disappear behind it for a third of the clip — the 4.00 m depth in the
    day-7 trace. Furniture here occludes from the *side*: partial, recoverable
    occlusion is the case worth testing, and total occlusion of every agent at
    once is not.

    **Speed is a set requirement now, not an accident.** Day 7 showed the
    envelope is speed-aware — 250 gate px of silhouette needed at 4 native
    px/frame against 92 px at 30 — so a set whose agents all walk at one speed
    exercises a single point on a curve. Path lengths here are chosen to spread
    image-plane speed from roughly 2 px/frame (below the background-absorption
    floor, where the gate cannot wake at any size) to roughly 26.
    """
    room = (10.0, 3.0, 14.0)

    def cam(
        name: str,
        position: tuple[float, float, float],
        yaw: float,
        covers: str,
        *,
        hd: bool = False,
        pitch: float = 16.0,
    ) -> CameraSpec:
        if hd:
            return CameraSpec(
                name, 1920, 1080, 1350.0, 1350.0, position, yaw, covers, pitch
            )
        return CameraSpec(name, 1280, 720, 900.0, 900.0, position, yaw, covers, pitch)

    # Primary pair, overlapping down the length of the room.
    cam_a = cam("cam_a", (-1.6, 2.6, 0.4), 6.0, "left half, looking down-room")
    cam_b = cam("cam_b", (1.6, 2.6, 0.4), -6.0, "right half, overlaps cam_a")
    cam_a_hd = cam(
        "cam_a_1080", (-1.6, 2.6, 0.4), 6.0, "1080p rendition of cam_a", hd=True
    )
    cam_b_hd = cam(
        "cam_b_1080", (1.6, 2.6, 0.4), -6.0, "1080p rendition of cam_b", hd=True
    )
    # Long view from the far end; agents recede rather than approach.
    cam_d = cam("cam_d", (0.0, 2.6, 13.6), 180.0, "far end, facing back down-room")

    # The coverage gap, kept deliberately. Pointed into a corner the walking
    # lane never enters, so its agents are genuinely unobservable rather than
    # merely small. Tagged hard_coverage at mint time.
    cam_gap = cam(
        "cam_gap",
        (4.6, 2.6, 13.4),
        105.0,
        "GAP: faces the side wall; the walking lane is outside its frustum",
    )

    # Occluders sit off-centre so they take a bite out of a sightline instead
    # of swallowing it. Partial occlusion is the testable case.
    furniture = [
        Furniture("desk_left", (-3.1, 0.4, 5.0), (1.6, 0.8, 0.9)),
        Furniture("desk_right", (3.1, 0.4, 6.5), (1.6, 0.8, 0.9)),
        Furniture("cabinet", (-3.4, 0.9, 9.0), (1.0, 1.8, 0.6)),
        Furniture("planter", (3.3, 0.6, 9.5), (0.8, 1.2, 0.8)),
    ]

    def lane(
        index: int, metres: float, count: int = 1, *, reverse: bool = False
    ) -> Agent:
        """One walker in the observable band, travelling ``metres`` in-clip.

        Path length is the speed control: the clip is a fixed number of frames,
        so a longer path is a faster agent. Roughly 0.5 m lands below the
        background-absorption floor and 14 m at the fast end of the measured
        envelope.

        Lateral spread is deliberately tight. The stereo pair sits 3.2 m apart,
        and at the near end of the band the horizontal half-FOV is only about
        3.5 m, so agents spread wide enough to look natural fall outside the
        *other* camera's frustum and get scored as coverage gaps that were
        never intended. Depth does the separating instead.
        """
        spread = 0.0 if count == 1 else (index / max(1, count - 1) - 0.5) * 1.8
        z_start = 5.0 + (index % 3) * 1.0
        z_end = z_start + (-metres if reverse else metres) * 0.4
        z_end = float(np.clip(z_end, 4.0, 11.0))
        x_start = spread
        # Lateral travel carries most of the image-plane speed, since a metre
        # across the view moves more pixels than a metre along it.
        x_end = spread + metres * 0.42 * (-1 if index % 2 else 1)
        return Agent(
            index, (x_start, z_start), (float(np.clip(x_end, -4.0, 4.0)), z_end)
        )

    def walkers(count: int, metres: float) -> list[Agent]:
        return [lane(i, metres, count) for i in range(count)]

    daylight = Condition.DAYLIGHT
    scenes: list[Scene] = []

    # --- Speed ladder: the same geometry at five speeds, so the envelope
    # curve is exercised end to end rather than at one point.
    for label, metres, note in (
        ("crawl", 0.5, "below the background-absorption floor; ~2 px/frame"),
        ("slow", 1.2, "near the 4 px/frame knee where 250 px is needed"),
        ("walk", 2.6, "mid-range, ~8 px/frame"),
        ("brisk", 4.5, "~15 px/frame"),
        ("fast", 8.0, "fast, past the envelope's flat region"),
        ("sprint", 14.0, "fast end of the measured curve, ~30 native px/frame"),
    ):
        scenes.append(
            Scene(
                f"speed_{label}_2agents",
                room,
                [cam_a, cam_b],
                walkers(2, metres),
                furniture,
                (daylight, Condition.SINGLE_PERSON),
                frames,
                fps,
                f"speed ladder: {note}",
                extra={"speed_band": label, "path_metres": metres},
            )
        )

    # --- Occupancy and occlusion.
    scenes.append(
        Scene(
            "crowded_6agents",
            room,
            [cam_a, cam_b],
            walkers(6, 3.4),
            furniture,
            (daylight, Condition.CROWDED, Condition.OCCLUSION_CROSSING),
            frames,
            fps,
            "6 agents, mutual occlusion, all inside the observable band",
            extra={"speed_band": "walk", "path_metres": 3.4},
        )
    )
    scenes.append(
        Scene(
            "furniture_occlusion_3agents",
            room,
            [cam_a, cam_d],
            walkers(3, 3.0),
            furniture,
            (daylight, Condition.OCCLUSION_FURNITURE),
            frames,
            fps,
            "paths clip the side furniture: partial, recoverable occlusion",
            extra={"speed_band": "walk", "path_metres": 3.0},
        )
    )
    scenes.append(
        Scene(
            "receding_2agents",
            room,
            [cam_d, cam_a],
            [lane(i, 4.0, 2, reverse=True) for i in range(2)],
            furniture,
            (daylight, Condition.FAR_FIELD),
            frames,
            fps,
            "agents recede from cam_d: shrinking silhouette across the envelope",
            extra={"speed_band": "brisk", "path_metres": 4.0},
        )
    )

    # --- 1080p renditions. Same scenes at a different raster: the envelope is
    # defined in gate pixels, so both must bucket identically.
    scenes.append(
        Scene(
            "hd_walk_2agents",
            room,
            [cam_a_hd, cam_b_hd],
            walkers(2, 2.6),
            furniture,
            (daylight, Condition.SINGLE_PERSON),
            frames,
            fps,
            "1080p rendition of the mid-speed case",
            extra={"speed_band": "walk", "path_metres": 2.6},
        )
    )
    scenes.append(
        Scene(
            "hd_far_field_3agents",
            room,
            [cam_a_hd],
            walkers(3, 5.0),
            furniture,
            (daylight, Condition.FAR_FIELD),
            frames,
            fps,
            "1080p, agents worked out to the far end of the band",
            extra={"speed_band": "brisk", "path_metres": 5.0},
        )
    )

    # --- Day-6 degenerates, retained.
    scenes.append(
        Scene(
            "lights_off_transient",
            room,
            [cam_a, cam_b],
            walkers(2, 3.2),
            furniture,
            (Condition.LIGHTS_TRANSIENT, Condition.EVENING_ARTIFICIAL),
            frames,
            fps,
            "lights cut mid-clip",
            lights_off_from=frames // 2,
            extra={"speed_band": "walk", "path_metres": 3.2},
        )
    )
    scenes.append(
        Scene(
            "blown_window",
            room,
            [cam_a, cam_b],
            walkers(2, 3.2),
            furniture,
            (Condition.GLARE, daylight),
            frames,
            fps,
            "blown-out window in frame",
            blown_window=True,
            extra={"speed_band": "walk", "path_metres": 3.2},
        )
    )
    scenes.append(
        Scene(
            "near_static",
            room,
            [cam_a],
            [Agent(0, (0.0, 6.0), (0.04, 6.0))],
            furniture,
            (Condition.EMPTY, daylight),
            frames,
            fps,
            "near-static: one agent barely moving, well under the floor",
            extra={"speed_band": "crawl", "path_metres": 0.04},
        )
    )

    # --- The coverage gap, kept on purpose. Tagged hard_coverage so it does
    # not drag the aggregate under the floor and does not get authored away.
    scenes.append(
        Scene(
            "coverage_gap_3agents",
            room,
            [cam_gap, cam_a],
            walkers(3, 3.6),
            furniture,
            (daylight, Condition.BLIND_SPOT_TRAVERSAL),
            frames,
            fps,
            "cam_gap faces the side wall; the lane is outside its frustum",
            extra={"speed_band": "walk", "path_metres": 3.6, "hard_camera": "cam_gap"},
        )
    )
    scenes.append(
        Scene(
            "coverage_gap_handoff",
            room,
            [cam_gap, cam_d],
            walkers(2, 5.5),
            furniture,
            (daylight, Condition.BLIND_SPOT_TRAVERSAL, Condition.OCCLUSION_CROSSING),
            frames,
            fps,
            "handoff across the gap: unobservable on cam_gap, observable on cam_d",
            extra={"speed_band": "fast", "path_metres": 5.5, "hard_camera": "cam_gap"},
        )
    )

    return scenes


def build_scenes_v4_gate(frames: int, fps: float) -> list[Scene]:
    """The v4-gate scene set: authored quiet, on purpose.

    Day 15 found that v3-indoor cannot evaluate a motion gate: its
    dataset.moving_frame_fraction is 0.9667 aggregate and 1.0000 in its
    "occupied" bucket, because v3 was authored under the same >=0.80
    observability floor as every other set — a floor that rewards agents
    who stay in frustum and moving, exactly the opposite of what a gate's
    entire product depends on (frames where nothing happens, correctly
    slept through). v4-gate is the fixture built for that instead: empty
    rooms, an agent that never moves, an agent that moves once and then
    stops, and a lights-off period with nobody in the room. Every scene
    here is tagged ``low_activity`` in its ``extra`` dict; see
    :func:`write_golden_from_manifest`.

    This does not touch v3's floor or v3's clips. v3 stays the instrument
    for a scene that is genuinely almost always moving; v4-gate is the
    instrument for a scene that almost never is. Neither one is the
    Tier-1 economic claim — see the Day-16 report.
    """
    room = (10.0, 3.0, 14.0)

    def cam(
        name: str, position: tuple[float, float, float], yaw: float, covers: str
    ) -> CameraSpec:
        return CameraSpec(name, 1280, 720, 900.0, 900.0, position, yaw, covers, 16.0)

    cam_a = cam("cam_a", (-1.6, 2.6, 0.4), 6.0, "left half, looking down-room")
    cam_b = cam("cam_b", (1.6, 2.6, 0.4), -6.0, "right half, overlaps cam_a")

    furniture = [
        Furniture("desk_left", (-3.1, 0.4, 5.0), (1.6, 0.8, 0.9)),
        Furniture("desk_right", (3.1, 0.4, 6.5), (1.6, 0.8, 0.9)),
    ]

    daylight = Condition.DAYLIGHT
    scenes: list[Scene] = []

    # --- Genuinely empty: zero agents. The renderer's own limitation makes
    # this the purest case it can produce — no sensor noise model means an
    # empty, unlit-change room renders bit-identical frame to frame, which
    # is a finding in its own right (see the Day-16 report), not hidden here.
    #
    # NOT tagged low_activity: an empty room is trivially NO_MOTION on every
    # frame, so it clears the observability floor on its own -- there is
    # nothing here for the exemption to do, and leaving it untagged is what
    # gives mint_golden_set's floor something to actually check (a set of
    # nothing but exemptions is refused; see MIN_OBSERVABLE_FRACTION).
    scenes.append(
        Scene(
            "empty_room",
            room,
            [cam_a, cam_b],
            [],
            furniture,
            (Condition.EMPTY, daylight),
            frames,
            fps,
            "zero agents: the purest quiet case this renderer can produce",
            extra={"speed_band": "none", "path_metres": 0.0},
        )
    )

    # --- Empty, plus a lights-off transient. Nobody is in the room when the
    # lights change, so this exercises "lights-off periods" without also
    # exercising occupancy -- the two are independent variables. Also left
    # untagged for the same reason: zero agents is trivially observable
    # regardless of what the lights do.
    scenes.append(
        Scene(
            "empty_room_lights_off",
            room,
            [cam_a],
            [],
            furniture,
            (Condition.EMPTY, Condition.LIGHTS_TRANSIENT, Condition.EVENING_ARTIFICIAL),
            frames,
            fps,
            "lights cut mid-clip in an otherwise empty room",
            lights_off_from=frames // 2,
            extra={"speed_band": "none", "path_metres": 0.0},
        )
    )

    # --- One occupant, speed_scale=0: position_at(t) returns `start` for
    # every t, so this agent is present in every frame and never moves --
    # "long static interval" with a body in frame, not an empty room.
    scenes.append(
        Scene(
            "long_static_occupant",
            room,
            [cam_a, cam_b],
            [Agent(0, (0.3, 6.0), (0.3, 6.0), speed_scale=0.0)],
            furniture,
            (Condition.SINGLE_PERSON, daylight),
            frames,
            fps,
            "one occupant present the whole clip, speed_scale=0: never moves",
            extra={"low_activity": True, "speed_band": "none", "path_metres": 0.0},
        )
    )

    # --- One occupant who arrives quickly and then stops: speed_scale=7.0
    # drives progress = min(1, t*7) to 1.0 by t=1/7 (~14% into the clip), so
    # motion is confined to the first few frames and the agent is static,
    # in frame, for the remaining ~86% -- "a single brief entry into an
    # otherwise still scene."
    scenes.append(
        Scene(
            "brief_entry",
            room,
            [cam_a, cam_b],
            [Agent(0, (-3.5, 6.0), (0.3, 6.0), speed_scale=7.0)],
            furniture,
            (Condition.SINGLE_PERSON, daylight),
            frames,
            fps,
            "agent walks in over the first ~1/7 of the clip, then stands still",
            extra={"low_activity": True, "speed_band": "crawl", "path_metres": 3.8},
        )
    )

    # --- Brief entry, plus a lights-off transient after the agent has
    # already settled -- two quiet-adjacent conditions in one clip, neither
    # masking the other.
    scenes.append(
        Scene(
            "brief_entry_evening",
            room,
            [cam_a],
            [Agent(0, (-3.5, 6.0), (0.3, 6.0), speed_scale=7.0)],
            furniture,
            (
                Condition.SINGLE_PERSON,
                Condition.LIGHTS_TRANSIENT,
                Condition.EVENING_ARTIFICIAL,
            ),
            frames,
            fps,
            "agent settles early, lights cut well after -- two quiet cues, not one",
            lights_off_from=(2 * frames) // 3,
            extra={"low_activity": True, "speed_band": "crawl", "path_metres": 3.8},
        )
    )

    return scenes


V5_CESSATION_EXEMPT_REGIMES = frozenset({"maneuver"})
"""v5-cessation's declared scope: cessation volume, not heading changes.
Genuinely exercising ~30 sustained-motion `maneuver` frames (per
classify_track's per-frame heading/speed-delta test) needs either dozens
of separate hand-authored turn events (one classified frame each) or a
continuously-curved path this file's straight-leg MultiSegmentAgent does
not model. Rather than contrive either just to clear a number, `maneuver`
is declared out of scope here — the SAME "declared, not accidental" rule
:class:`~src.data.golden.GoldenClip`'s `low_activity` flag already
enforces, extended to a regime instead of a clip. v3-indoor set the
precedent: "maneuver is empty on both sets by construction, not by
omission" (Day 21). Its actual count is still measured and reported by
:func:`enforce_regime_volume` -- declared-out-of-scope is not
hidden-and-unmeasured."""


def _stop_event_scene(
    scene_name: str,
    room: tuple[float, float, float],
    camera: CameraSpec,
    furniture: list[Furniture],
    conditions: tuple[Condition, ...],
    fps: float,
    start_xz: tuple[float, float],
    end_xz: tuple[float, float],
    approach_seconds: float,
    stop_seconds: float,
    ease_out: bool,
    notes: str,
    restart_end_xz: tuple[float, float] | None = None,
    restart_seconds: float | None = None,
    second_stop_seconds: float | None = None,
) -> Scene:
    """One agent: walk ``start_xz`` -> ``end_xz`` over ``approach_seconds``,
    hold at ``end_xz`` for ``stop_seconds``. If ``restart_end_xz`` is given,
    walk on to it over ``restart_seconds`` and hold there for
    ``second_stop_seconds`` -- the stop-then-restart shape Day 23,
    Objective 2 asks for, built from the same primitive as a single stop
    (one more walk leg, one more pause leg).

    All of the day's varied dimensions are just this function's own
    parameters, made concrete per call site in
    :func:`build_scenes_v5_cessation`: ``approach_seconds`` (approach
    speed, given the leg's distance), ``ease_out`` (deceleration profile),
    ``stop_seconds`` (stop duration), and ``start_xz``/``end_xz`` relative
    to ``camera`` (distance and radial-vs-lateral direction).
    """
    seconds = [approach_seconds, stop_seconds]
    is_restart = restart_end_xz is not None
    if is_restart:
        assert restart_seconds is not None and second_stop_seconds is not None
        seconds += [restart_seconds, second_stop_seconds]
    fractions = _seconds_to_path_fractions(seconds)

    segments = [
        PathSegment(end=end_xz, duration=fractions[0], ease_out=ease_out),
        PathSegment(end=end_xz, duration=fractions[1]),  # pause: zero-length leg
    ]
    if is_restart:
        assert restart_end_xz is not None
        segments += [
            PathSegment(end=restart_end_xz, duration=fractions[2], ease_out=ease_out),
            PathSegment(end=restart_end_xz, duration=fractions[3]),  # pause
        ]

    frame_count = max(2, int(round(sum(seconds) * fps)))
    agent = MultiSegmentAgent(agent_id=0, start=start_xz, segments=segments)

    path_metres = float(np.hypot(end_xz[0] - start_xz[0], end_xz[1] - start_xz[1]))
    if is_restart:
        assert restart_end_xz is not None
        path_metres += float(
            np.hypot(restart_end_xz[0] - end_xz[0], restart_end_xz[1] - end_xz[1])
        )

    return Scene(
        scene_name,
        room,
        [camera],
        [agent],
        furniture,
        conditions,
        frame_count,
        fps,
        notes,
        extra={
            "speed_band": "cessation-varied",
            "path_metres": round(path_metres, 2),
        },
    )


def build_scenes_v5_cessation(frames: int, fps: float) -> list[Scene]:
    """The v5-cessation scene set: cessation volume, on purpose (Day 23).

    Day 21's cessation diagnosis and Day 22's four-way comparison both
    rested on v4.1-gate's ``brief_entry`` family — three clips sharing, in
    substance, two distinct GT trajectories (two of the three are
    identical GT, differing only in lighting). Day 23 Objective 1 fixed
    the regime LABEL (the recovery tail was hiding inside "static"), which
    raised v4.1-gate's own cessation count from 3 to 39 frames -- but 39
    frames from ~2 underlying stop events is a labeling fix, not
    behavioral diversity. This set supplies the diversity: walk-then-stop
    repeated at volume, varying approach speed, deceleration profile
    (abrupt vs gradual, :class:`PathSegment`'s ``ease_out``), stop
    duration, distance from camera, and direction relative to the optical
    axis (radial vs lateral -- these stress the measurement model
    differently: a radial approach changes distance-from-camera, and
    therefore R, throughout the walk; a lateral crossing at fixed depth
    does not), plus stop-then-restart sequences. ``frames``, the value
    every other builder in this file takes uniformly from the CLI, is
    accepted for signature parity but not used uniformly here -- each
    scene is sized in SECONDS (via :func:`_stop_event_scene`) to fit its
    own walk/stop timing, since a fixed global frame count cannot fit a
    1.2s fast approach and a 4s stop hold in the same clip without either
    truncating the stop or padding the approach.

    ``frames`` in :func:`generate`'s CLI is a MINIMUM only here, unused by
    any call in this function directly (every clip supplies its own).
    """
    room = (10.0, 3.0, 14.0)
    daylight = Condition.DAYLIGHT
    far = Condition.FAR_FIELD

    cam_radial = CameraSpec(
        "cam_radial",
        1280,
        720,
        900.0,
        900.0,
        (0.0, 2.6, 0.4),
        0.0,
        "looking straight down-room; radial approach/retreat view",
        16.0,
    )
    # yaw=-90 rotates this camera's view axis onto world +x -- so, exactly
    # like cam_radial's own axis (world +z) above, DEPTH from cam_lateral
    # is a function of X, and its HORIZONTAL image axis is a function of Z.
    # A genuine lateral crossing (perpendicular to THIS camera's optical
    # axis) therefore varies Z at roughly fixed X, not the other way
    # around -- verified empirically (project() swept across the room)
    # before picking the coordinates below, the same way cam_radial's own
    # near-distance floor (z >= ~3m; closer clips the frame given this
    # room's fixed camera height/pitch) was found empirically rather than
    # assumed.
    cam_lateral = CameraSpec(
        "cam_lateral",
        1280,
        720,
        900.0,
        900.0,
        (-6.5, 2.6, 6.0),
        -90.0,
        "mounted on the side wall, looking across the room width; lateral view",
        14.0,
    )
    # Off the primary radial (x~0) and lateral (z~3-9) traversal lanes, so
    # it adds occlusion realism without accidentally blocking the very
    # events this set exists to render.
    furniture = [Furniture("desk", (4.3, 0.4, 2.0), (1.2, 0.8, 0.8))]

    def person(*extra: Condition) -> tuple[Condition, ...]:
        return (Condition.SINGLE_PERSON, daylight, *extra)

    scenes: list[Scene] = []

    # --- Radial: walking toward/away from cam_radial along z (camera at
    # z=0.4). z >= ~3.5m throughout keeps the agent in frame at this
    # camera's fixed height/pitch -- verified empirically, see above.
    radial_specs = [
        # (name, start, end, approach_s, stop_s, ease_out, extra_conditions)
        ("radial_slow_near_abrupt", (0.3, 10.5), (0.3, 4.5), 3.0, 1.5, False, ()),
        ("radial_slow_far_gradual", (0.3, 4.5), (0.3, 11.0), 3.0, 1.5, True, (far,)),
        ("radial_medium_near_gradual", (-0.5, 9.5), (-0.5, 4.0), 2.0, 2.0, True, ()),
        (
            "radial_medium_far_abrupt",
            (-0.5, 4.0),
            (-0.5, 10.5),
            2.0,
            2.0,
            False,
            (far,),
        ),
        ("radial_fast_near_abrupt", (0.8, 8.5), (0.8, 4.2), 1.2, 1.5, False, ()),
        ("radial_fast_far_gradual", (0.8, 4.2), (0.8, 9.8), 1.2, 1.5, True, (far,)),
        ("radial_long_stop_near", (-0.2, 9.8), (-0.2, 4.3), 2.2, 4.0, False, ()),
        ("radial_long_stop_far", (-0.2, 4.3), (-0.2, 10.8), 2.2, 4.0, True, (far,)),
    ]
    for name, start, end, approach_s, stop_s, ease, extra in radial_specs:
        scenes.append(
            _stop_event_scene(
                name,
                room,
                cam_radial,
                furniture,
                person(*extra),
                fps,
                start,
                end,
                approach_s,
                stop_s,
                ease,
                f"radial {'gradual' if ease else 'abrupt'} stop, "
                f"approach {approach_s}s, hold {stop_s}s",
            )
        )

    # --- Lateral: crossing cam_lateral's view along z, at fixed x (which
    # sets distance from the camera -- NEAR_X/FAR_X below, both verified
    # to keep depth >= ~3m, the same floor cam_radial's z needs).
    NEAR_X, FAR_X = -1.5, 3.2
    lateral_specs = [
        ("lateral_slow_near_abrupt", (NEAR_X, 3.0), (NEAR_X, 8.5), 3.0, 1.5, False, ()),
        (
            "lateral_slow_far_gradual",
            (FAR_X, 3.0),
            (FAR_X, 8.5),
            3.0,
            1.5,
            True,
            (far,),
        ),
        (
            "lateral_medium_near_gradual",
            (NEAR_X, 8.5),
            (NEAR_X, 3.5),
            2.0,
            2.0,
            True,
            (),
        ),
        (
            "lateral_medium_far_abrupt",
            (FAR_X, 8.5),
            (FAR_X, 3.5),
            2.0,
            2.0,
            False,
            (far,),
        ),
        ("lateral_fast_near_gradual", (NEAR_X, 3.5), (NEAR_X, 8.0), 1.2, 1.5, True, ()),
        (
            "lateral_fast_far_abrupt",
            (FAR_X, 3.5),
            (FAR_X, 8.0),
            1.2,
            1.5,
            False,
            (far,),
        ),
        (
            "lateral_long_stop_near",
            (NEAR_X, 8.5),
            (NEAR_X, 3.2),
            2.2,
            4.0,
            False,
            (),
        ),
        ("lateral_long_stop_far", (FAR_X, 8.5), (FAR_X, 3.2), 2.2, 4.0, True, (far,)),
    ]
    for name, start, end, approach_s, stop_s, ease, extra in lateral_specs:
        scenes.append(
            _stop_event_scene(
                name,
                room,
                cam_lateral,
                furniture,
                person(*extra),
                fps,
                start,
                end,
                approach_s,
                stop_s,
                ease,
                f"lateral {'gradual' if ease else 'abrupt'} crossing-stop, "
                f"approach {approach_s}s, hold {stop_s}s",
            )
        )

    # --- Stop-then-restart: a second cessation event per clip, the shape
    # Objective 2 explicitly asks for.
    scenes.append(
        _stop_event_scene(
            "stop_then_restart_radial",
            room,
            cam_radial,
            furniture,
            person(),
            fps,
            (0.5, 10.5),
            (0.5, 6.0),
            2.0,
            1.5,
            False,
            "radial: walk, stop, restart further in, stop again",
            restart_end_xz=(0.5, 4.0),
            restart_seconds=1.5,
            second_stop_seconds=1.0,
        )
    )
    scenes.append(
        _stop_event_scene(
            "stop_then_restart_lateral",
            room,
            cam_lateral,
            furniture,
            person(),
            fps,
            (NEAR_X, 3.5),
            (NEAR_X, 7.5),
            1.8,
            1.5,
            True,
            "lateral: walk, stop, restart the other way, stop again",
            restart_end_xz=(NEAR_X, 5.0),
            restart_seconds=1.6,
            second_stop_seconds=1.0,
        )
    )
    scenes.append(
        _stop_event_scene(
            "double_stop_radial",
            room,
            cam_radial,
            furniture,
            person(),
            fps,
            (-0.3, 9.5),
            (-0.3, 6.5),
            1.5,
            1.2,
            False,
            "radial: walk, brief stop, walk on, long final stop",
            restart_end_xz=(-0.3, 4.3),
            restart_seconds=1.3,
            second_stop_seconds=3.0,
        )
    )

    return scenes


def build_scenes(frames: int, fps: float) -> list[Scene]:
    """The scene set: coverage, overlap, a gap, and degenerates."""
    room = (8.0, 3.0, 12.0)

    # A camera pair with genuine overlap, plus a third with a deliberate
    # coverage gap between it and the pair. Both are things annotation cannot
    # add later: cross-camera association GT needs the overlap, and blind-spot
    # handoff eval needs the gap.
    cam_a_720 = CameraSpec(
        "cam_a",
        1280,
        720,
        900.0,
        900.0,
        (-2.0, 2.6, 0.0),
        15.0,
        "left half, overlaps cam_b",
    )
    cam_b_720 = CameraSpec(
        "cam_b",
        1280,
        720,
        900.0,
        900.0,
        (2.0, 2.6, 0.0),
        -15.0,
        "right half, overlaps cam_a",
    )
    cam_c_720 = CameraSpec(
        "cam_c",
        1280,
        720,
        900.0,
        900.0,
        (0.0, 2.6, 11.0),
        180.0,
        "far end; a coverage GAP separates it from the pair",
    )
    cam_a_1080 = CameraSpec(
        "cam_a_1080",
        1920,
        1080,
        1350.0,
        1350.0,
        (-2.0, 2.6, 0.0),
        15.0,
        "1080p rendition of cam_a",
    )

    desks = [
        Furniture("desk_1", (-1.5, 0.4, 4.0), (1.6, 0.8, 0.8)),
        Furniture("desk_2", (1.8, 0.4, 5.5), (1.6, 0.8, 0.8)),
        Furniture("partition", (0.0, 0.9, 7.0), (2.4, 1.8, 0.15)),
    ]

    def walkers(count: int) -> list[Agent]:
        return [
            Agent(i, (-3.0 + 1.4 * i, 2.0), (3.0 - 1.0 * i, 9.5), speed_scale=1.0)
            for i in range(count)
        ]

    return [
        Scene(
            "overlap_pair_2agents",
            room,
            [cam_a_720, cam_b_720],
            walkers(2),
            desks,
            (
                Condition.DAYLIGHT,
                Condition.SINGLE_PERSON,
                Condition.OCCLUSION_FURNITURE,
            ),
            frames,
            fps,
            "camera pair with overlap; 2 agents behind desks",
        ),
        Scene(
            "coverage_gap_3agents",
            room,
            [cam_a_720, cam_c_720],
            walkers(3),
            desks,
            (
                Condition.DAYLIGHT,
                Condition.BLIND_SPOT_TRAVERSAL,
                Condition.OCCLUSION_CROSSING,
            ),
            frames,
            fps,
            "deliberate coverage gap between cam_a and cam_c",
        ),
        Scene(
            "crowded_6agents",
            room,
            [cam_a_720],
            walkers(6),
            desks,
            (Condition.DAYLIGHT, Condition.CROWDED, Condition.OCCLUSION_CROSSING),
            frames,
            fps,
            "6 agents, heavy mutual occlusion",
        ),
        Scene(
            "far_field_1080p",
            room,
            [cam_a_1080],
            walkers(2),
            desks,
            (Condition.DAYLIGHT, Condition.FAR_FIELD),
            frames,
            fps,
            "1080p rendition; agents at the far end of the envelope",
        ),
        Scene(
            "lights_off_transient",
            room,
            [cam_a_720],
            walkers(2),
            desks,
            (Condition.LIGHTS_TRANSIENT, Condition.EVENING_ARTIFICIAL),
            frames,
            fps,
            "lights cut mid-clip",
            lights_off_from=frames // 2,
        ),
        Scene(
            "blown_window",
            room,
            [cam_a_720],
            walkers(2),
            desks,
            (Condition.GLARE, Condition.DAYLIGHT),
            frames,
            fps,
            "blown-out window in frame",
            blown_window=True,
        ),
        Scene(
            "near_static",
            room,
            [cam_a_720],
            [Agent(0, (0.0, 6.0), (0.05, 6.0), speed_scale=1.0)],
            desks,
            (Condition.EMPTY, Condition.DAYLIGHT),
            frames,
            fps,
            "near-static: one agent barely moving",
        ),
    ]


def _count_moving_frames(agent_xyz: np.ndarray, eps: float = 1e-6) -> int:
    """How many frames contain real world-space displacement by any agent.

    Was hardcoded to ``scene.frames`` (every clip claimed 100% moving,
    regardless of what was actually in it) until Day 16, when a dataset
    whose entire point is to be quiet made that specific dishonesty
    impossible to carry forward unnoticed. Frame 0 is never "moving": there
    is no previous frame to have moved from, the same convention
    :func:`src.data.scorecard.world_motion` uses.
    """
    if agent_xyz.shape[1] == 0 or agent_xyz.shape[0] < 2:
        return 0
    displacement = np.linalg.norm(np.diff(agent_xyz, axis=0), axis=2)
    return int(np.sum(np.any(displacement > eps, axis=1)))


def _speed_summary(track_uv: np.ndarray, native_width: int) -> dict[str, float]:
    """Per-clip image-plane speed, in gate pixels per frame.

    Recorded in the manifest because the capability envelope is a function of
    speed. Reported in *gate* pixels so a 1080p clip and its 720p twin are
    directly comparable, which is the space the envelope is defined in.
    """
    if track_uv.size == 0 or track_uv.shape[0] < 2:
        return {"median": 0.0, "min": 0.0, "max": 0.0}
    to_gate = 320.0 / native_width
    steps = np.linalg.norm(np.diff(track_uv, axis=0), axis=2) * to_gate
    finite = steps[np.isfinite(steps)]
    if finite.size == 0:
        return {"median": 0.0, "min": 0.0, "max": 0.0}
    return {
        "median": round(float(np.median(finite)), 3),
        "min": round(float(np.min(finite)), 3),
        "max": round(float(np.max(finite)), 3),
    }


def sha256_array(array: np.ndarray) -> str:
    digest = hashlib.sha256()
    digest.update(str(array.shape).encode())
    digest.update(str(array.dtype).encode())
    digest.update(np.ascontiguousarray(array).tobytes())
    return digest.hexdigest()


def generate(
    output_root: Path,
    frames: int,
    fps: float,
    seed: int,
    scene_set: str = "v2",
) -> dict[str, Any]:
    """Render every scene and write clips plus exact GT.

    Args:
        scene_set: which authored scene set to render. ``v2`` is frozen — its
            content hashes are cited by ``configs/golden/v2-indoor.golden.json``
            and must keep reproducing byte-for-byte, so it is never edited.
            ``v3`` is the re-authored set whose GT is actually observable.
            ``v4-gate`` is authored quiet, to measure a motion gate rather
            than tracking or depth (Day 16). ``v4.1-gate`` is the same
            scenes re-rendered under the Day-17 gait-phase fix — see
            :data:`DATASET_NAMES`.
    """
    builders = {
        "v2": build_scenes,
        "v3": build_scenes_v3,
        "v4-gate": build_scenes_v4_gate,
        "v4.1-gate": build_scenes_v4_gate,
        "v5-cessation": build_scenes_v5_cessation,
    }
    if scene_set not in builders:
        raise ValueError(
            f"unknown scene_set {scene_set!r}; expected one of "
            f"{sorted(builders)}. Scene sets are versioned rather than edited "
            "because a frozen golden set cites the bytes this produces."
        )
    scenes = builders[scene_set](frames, fps)
    output_root.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    for scene in scenes:
        for camera in scene.cameras:
            clip_id = f"{scene.name}__{camera.name}"
            # Python's hash() is salted per process (PYTHONHASHSEED), so using
            # it here made content_sha irreproducible across runs — which
            # defeats the entire point of a content-addressed golden set.
            # blake2s is stable everywhere.
            stream = int.from_bytes(
                hashlib.blake2s(clip_id.encode(), digest_size=4).digest(), "big"
            )
            rng = np.random.default_rng(seed + stream % 10_000)

            # Surface texture belongs to the wall, not to the moment. Drawing
            # it inside the frame loop resampled it every frame, which put
            # sigma=3 grain on 83% of pixels of a static scene and silently
            # turned "surface texture" into undeclared sensor noise that the
            # motion gate was then scored against.
            texture = rng.normal(0.0, 3.0, size=(camera.height, camera.width))

            rgb_stack, depth_stack, inst_stack = [], [], []
            agent_xyz, track_uv, track_occ = [], [], []

            for frame in range(scene.frames):
                out = render_frame(scene, camera, frame, texture)
                rgb_stack.append(out["rgb"])
                depth_stack.append(out["depth_m"])
                inst_stack.append(out["instances"])

                t = frame / max(1, scene.frames - 1)
                positions, uvs, occluded = [], [], []
                for agent in scene.agents:
                    world = agent.position_at(t)
                    u, v, _z = project(world, camera)
                    positions.append(world)
                    uvs.append([u, v])
                    hidden = any(
                        f.occludes(world, np.array(camera.position))
                        for f in scene.furniture
                    )
                    off_frame = not (
                        0 <= u < camera.width and 0 <= v < camera.height
                    ) or not np.isfinite(u)
                    occluded.append(bool(hidden or off_frame))
                agent_xyz.append(positions)
                track_uv.append(uvs)
                track_occ.append(occluded)

            clip_path = output_root / f"{clip_id}.npz"
            n_agents = len(scene.agents)
            # np.asarray on a list of per-frame EMPTY position/uv lists infers
            # shape (T, 0), not (T, 0, 3)/(T, 0, 2) -- numpy has nothing to
            # read the trailing dimension from when the axis itself is empty.
            # Explicit reshape is a no-op when there are agents and fixes the
            # zero-agent case, which nothing exercised before v4-gate's
            # empty_room scene.
            payload = {
                "rgb": np.stack(rgb_stack),
                "depth_m": np.stack(depth_stack),
                "instances": np.stack(inst_stack),
                "agent_xyz": np.asarray(agent_xyz, dtype=np.float32).reshape(
                    scene.frames, n_agents, 3
                ),
                "track_uv": np.asarray(track_uv, dtype=np.float32).reshape(
                    scene.frames, n_agents, 2
                ),
                "track_occluded": np.asarray(track_occ, dtype=bool),
                "intrinsics": np.array(
                    [camera.fx, camera.fy, camera.cx, camera.cy], dtype=np.float64
                ),
                "extrinsics": camera.extrinsics(),
            }
            np.savez_compressed(clip_path, **payload)
            moving_frames = _count_moving_frames(payload["agent_xyz"])

            records.append(
                {
                    "clip_id": clip_id,
                    "scene": scene.name,
                    "camera": camera.name,
                    "covers": camera.covers,
                    "resolution": [camera.width, camera.height],
                    "frames": scene.frames,
                    "fps": fps,
                    "agents": len(scene.agents),
                    "conditions": [c.value for c in scene.conditions],
                    "notes": scene.notes,
                    "content_sha": sha256_array(payload["rgb"]),
                    "depth_sha": sha256_array(payload["depth_m"]),
                    "moving_frames": moving_frames,
                    "size_bytes": clip_path.stat().st_size,
                    # Image-plane speed decides where the capability envelope
                    # sits (day 7), so a set that does not record its speed
                    # distribution cannot say which part of the curve it
                    # exercised.
                    "speed_band": scene.extra.get("speed_band", "unspecified"),
                    "path_metres": scene.extra.get("path_metres"),
                    "track_speed_gate_px": _speed_summary(
                        np.asarray(payload["track_uv"]), camera.width
                    ),
                    "hard_coverage": scene.extra.get("hard_camera") == camera.name,
                    "low_activity": bool(scene.extra.get("low_activity", False)),
                }
            )
            print(
                f"  {clip_id:34} {camera.width}x{camera.height} "
                f"{scene.frames}f  {clip_path.stat().st_size/1e6:5.1f} MB"
            )

    manifest = {
        "schema_version": "1.0",
        "dataset": DATASET_NAMES[scene_set],
        "scene_set": scene_set,
        "lane": "S",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/gen_synthetic_indoor.py",
        "seed": seed,
        "renderer": {
            "kind": "analytic primitives (not Kubric, not photorealistic)",
            "why_not_kubric": (
                "Kubric 0.1.1 pins the Blender 2.93/3.x-era bpy API; the "
                "available Blender is 4.5, and the official path is a "
                "multi-gigabyte Docker image. Analytic primitives give EXACT "
                "closed-form depth and occlusion instead of rendered-and-read-"
                "back GT, which is a real advantage for geometry — at the cost "
                "of any appearance realism."
            ),
            "limitations": (
                "No global illumination, no material response, no lens model, "
                "and NO sensor noise at all: surface texture is fixed per "
                "camera, so a static scene produces bit-identical frames. A "
                "motion-gate score here therefore measures the gate against "
                "clean input and is an UPPER BOUND on real-camera precision. "
                "A number measured here is a GEOMETRY and MOTION number, not "
                "an appearance one."
            ),
        },
        "asset_clearance": ASSET_CLEARANCE,
        "supersession": (
            "SYNTHETIC-ONLY BASELINE. Real indoor footage from Site Zero "
            "supersedes this for every product claim. A scorecard computed "
            "against this dataset MUST NOT be quoted externally."
        ),
        "ground_truth": [
            "depth_m: per-pixel metric depth, analytic",
            "agent_xyz: per-frame 3D agent positions, metres",
            "track_uv: per-frame projected agent pixel coordinates",
            "track_occluded: per-frame occlusion flag, analytic slab test",
            "instances: per-pixel instance segmentation",
            "intrinsics / extrinsics: exact, not estimated",
        ],
        "clips": records,
    }
    (output_root / "dataset_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return manifest


def _supersession_for(version: str) -> str | None:
    """Which golden set ``version`` replaces as the active instrument.

    Wrong here is not cosmetic: it is the only record of which set a reader
    should stop quoting.

    v4-gate supersedes nothing — it measures a different capability (the
    gate) than v2/v3 measure (tracking, depth, geometry), so it is a
    parallel instrument, not a successor.

    v4.1-gate (Day 17) DOES supersede v4-gate: same scenes, same capability,
    re-rendered because v4-gate's gait-animation defect contaminated its own
    headline metrics — the one case here where a new set exists specifically
    because the old one should stop being quoted, not because it measures
    something new.

    v5-cessation (Day 23) supersedes nothing, the same reason v4-gate does
    not: it measures a different thing (cessation-regime volume) than
    v3/v4.1-gate measure, so it is a parallel instrument, not a successor.
    """
    if version == "v4.1-gate":
        return "v4-gate"
    if version == "v4-gate":
        return None
    if version == "v5-cessation":
        return None
    return {"v2-indoor": "v1-driving"}.get(version, "v2-indoor")


class RegimeVolumeError(RuntimeError):
    """Raised when a golden set cannot support the per-regime frame counts
    it exists to score — see :func:`enforce_regime_volume`."""


def enforce_regime_volume(
    clip_root: Path,
    manifest: dict[str, Any],
    min_cessation_frames: int,
    min_other_regime_frames: int = 30,
    exempt_regimes: frozenset[str] = frozenset(),
) -> dict[str, int]:
    """Refuse to mint a golden set whose own purpose (a specific motion
    regime, in volume) it cannot actually support — the same mechanism as
    :data:`src.data.golden.MIN_OBSERVABLE_FRACTION`'s floor and the
    ``low_activity`` exemption: acceptance is MEASURED from the bytes just
    written, not asserted, and a set that fails is refused rather than
    minted with a caveat.

    Regime counts are computed on every RAW frame of every agent track in
    the manifest (:func:`~src.estimator.regime.classify_track`) — the
    dataset's own composition, not ``scripts/eval_estimator.py``'s later
    SCORED subset (which additionally drops each track's first two frames
    to give every compared baseline a fair, non-circular start — see that
    script's module docstring). This check answers "does this dataset
    contain the phenomenon", not "how many frames will a specific
    evaluation protocol score" — the two numbers are related but not
    identical, and a reader comparing them should expect the raw count
    here to run slightly ahead of eval_estimator.py's reported one.

    Args:
        min_cessation_frames: The volume floor cessation specifically must
            clear — this function's whole reason to exist (Day 23,
            Objective 2): a set authored for cessation volume that does
            not actually reach it has failed at its own purpose.
        min_other_regime_frames: Floor every OTHER non-exempt regime must
            clear, so a set built for one regime's volume does not ship
            silently thin everywhere else.
        exempt_regimes: Regimes explicitly declared out of scope for this
            set's design — e.g. ``maneuver`` for a cessation-focused set
            with no authored heading changes. Declared by the CALLER
            (scene-authoring intent, not a post-hoc excuse for a set that
            merely came out thin) — the same discipline
            :class:`~src.data.golden.GoldenClip`'s ``low_activity`` flag
            already requires, extended from clip-level to regime-level.

    Returns:
        The measured per-regime frame counts, for the manifest/report to
        cite — reported even when the check passes, never computed and
        then thrown away.

    Raises:
        RegimeVolumeError: if cessation, or any non-exempt regime, falls
            below its floor.
    """
    from src.estimator.regime import MOTION_REGIMES, classify_track

    counts: dict[str, int] = {regime: 0 for regime in MOTION_REGIMES}
    for record in manifest["clips"]:
        clip_path = clip_root / f"{record['clip_id']}.npz"
        with np.load(clip_path) as data:
            agent_xyz = np.asarray(data["agent_xyz"], dtype=np.float64)
        dt_s = 1.0 / float(record["fps"])
        for agent_index in range(agent_xyz.shape[1]):
            track = agent_xyz[:, agent_index, :]
            for regime in classify_track(track, dt_s):
                counts[regime] += 1

    failures = []
    if counts.get("cessation", 0) < min_cessation_frames:
        failures.append(
            f"cessation: {counts.get('cessation', 0)} frames, needs "
            f">= {min_cessation_frames}"
        )
    for regime in MOTION_REGIMES:
        if regime == "cessation" or regime in exempt_regimes:
            continue
        if counts.get(regime, 0) < min_other_regime_frames:
            failures.append(
                f"{regime}: {counts.get(regime, 0)} frames, needs "
                f">= {min_other_regime_frames}"
            )
    if failures:
        raise RegimeVolumeError(
            "regime volume requirement not met -- this set cannot score "
            "the criterion it exists for and must not mint:\n  "
            + "\n  ".join(failures)
            + f"\nmeasured counts: {counts}"
        )
    return counts


def write_golden_from_manifest(
    manifest: dict[str, Any],
    version: str,
    config: Any,
    clip_root: Path,
    regime_volume: dict[str, Any] | None = None,
) -> Path:
    """Mint a golden set from a freshly generated manifest.

    The content hashes in a golden set are its whole value, so they must come
    from the generator that produced the bytes rather than from a person
    pasting them. Overwrite is permitted here only because a synthetic set is
    regenerable by definition; a set containing captured footage is immutable
    and must go through ``GoldenSet.with_clips`` under a new version.

    Args:
        regime_volume: When set, keyword arguments forwarded to
            :func:`enforce_regime_volume` — the check runs BEFORE
            ``mint_golden_set``, so a set that fails it is refused before
            the observability floor is even measured. ``None`` (the
            default, and every pre-Day-23 caller's behavior) skips it
            entirely — v3/v4-gate/v4.1-gate never gain a check they were
            never designed against.
    """
    if regime_volume is not None:
        measured_regime_counts = enforce_regime_volume(
            clip_root, manifest, **regime_volume
        )
        manifest["regime_counts"] = measured_regime_counts

    from src.data.golden import (
        Condition,
        Domain,
        GoldenClip,
        GoldenSet,
        Status,
        mint_golden_set,
    )

    dataset_name = manifest.get("dataset", DATASET_NAME)
    clips = tuple(
        GoldenClip(
            clip_id=record["clip_id"],
            content_sha=record["content_sha"],
            conditions=tuple(Condition(c) for c in record["conditions"]),
            source_dataset=dataset_name,
            notes=f"{record['camera']} {record['resolution'][0]}x"
            f"{record['resolution'][1]}, {record['agents']} agents, "
            f"speed {record.get('speed_band', 'unspecified')} "
            f"(median {record.get('track_speed_gate_px', {}).get('median', 0):.2f} "
            f"gate px/frame) — {record['covers']}",
            hard_coverage=bool(record.get("hard_coverage", False)),
            low_activity=bool(record.get("low_activity", False)),
        )
        for record in manifest["clips"]
    )
    golden = GoldenSet(
        version=version,
        domain=Domain.INDOOR,
        status=Status.ACTIVE,
        clips=clips,
        # What this set replaces as the active instrument. Wrong here is not
        # cosmetic: it is the only record of which set a reader should stop
        # quoting.
        supersedes=_supersession_for(version),
        description=(
            "SYNTHETIC-ONLY. Generated by scripts/gen_synthetic_indoor.py "
            "--write-golden. Superseded by Site Zero footage for any product "
            "claim; scores from it must not be quoted externally."
        ),
    )
    # Acceptance is measured here, not asserted. Every clip's observable
    # fraction is computed from the bytes just written, and mint_golden_set
    # refuses the set if the aggregate over non-hard_coverage clips falls below
    # the floor. v2 reached 0.4444 precisely because nothing measured this
    # before the manifest was written.
    observable = measure_observable_fractions(clip_root, manifest)
    for record in manifest["clips"]:
        record["observable_fraction"] = round(observable[record["clip_id"]], 4)

    result = mint_golden_set(
        config.paths.project_root / "configs" / "golden", golden, observable, True
    )
    if regime_volume is not None:
        # Persist regime_counts (and observable_fraction, already computed
        # above) back to the manifest this specific caller opted into the
        # extra check for -- v3/v4-gate/v4.1-gate's manifests are
        # unaffected, since they never pass regime_volume and this branch
        # never runs for them.
        (clip_root / "dataset_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n"
        )
    return result


def measure_observable_fractions(
    clip_root: Path, manifest: dict[str, Any]
) -> dict[str, float]:
    """Share of each clip's presented frames whose GT motion is observable.

    Uses the same partition the scorecard uses, so the number the acceptance
    floor checks is the number the scorecard will later report — not a
    parallel estimate that could drift away from it.
    """
    from src.data.scorecard import Observability, observability_partition

    config = IronConfig.load()
    gate_config = config.cascade.motion_gate_config()

    fractions: dict[str, float] = {}
    for record in manifest["clips"]:
        clip_id = record["clip_id"]
        partition = observability_partition(clip_root / f"{clip_id}.npz", gate_config)
        labels = partition.after_warmup()
        presented = int(labels.size)
        if not presented:
            fractions[clip_id] = 0.0
            continue
        scoreable = int(
            np.sum(
                (labels == Observability.NO_MOTION)
                | (labels == Observability.ABOVE_ENVELOPE)
            )
        )
        fractions[clip_id] = scoreable / presented
    return fractions


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frames", type=int, default=24)
    parser.add_argument("--fps", type=float, default=12.0)
    parser.add_argument("--seed", type=int, default=20260801)
    parser.add_argument("--output", default=None)
    parser.add_argument(
        "--scene-set",
        default="v2",
        choices=["v2", "v3", "v4-gate", "v4.1-gate", "v5-cessation"],
        help=(
            "which authored scene set to render. v2 is frozen — its bytes are "
            "cited by a golden manifest — so re-authoring means a new set. "
            "v4-gate is authored quiet, to measure a motion gate. v4.1-gate "
            "is v4-gate's scenes re-rendered under the Day-17 gait-phase fix. "
            "v5-cessation is authored for cessation-regime volume (Day 23)."
        ),
    )
    parser.add_argument(
        "--write-golden",
        metavar="VERSION",
        default=None,
        help=(
            "Mint a golden set of this version from the manifest. Without "
            "this the golden set can only be built by hand, and a hand-built "
            "set of content hashes is one that nobody can reproduce."
        ),
    )
    args = parser.parse_args(argv)

    config = IronConfig.load()
    dataset_name = DATASET_NAMES.get(args.scene_set, DATASET_NAME)
    output = (
        Path(args.output)
        if args.output
        else config.paths.resolved_data_dir / "synthetic" / dataset_name
    )

    print(f"Generating {dataset_name} -> {output}")
    print("Renderer: analytic primitives (see manifest for why not Kubric)\n")
    manifest = generate(
        output, args.frames, args.fps, args.seed, scene_set=args.scene_set
    )

    print(f"\n{len(manifest['clips'])} clips written.")
    print(f"Manifest: {output / 'dataset_manifest.json'}")

    if args.write_golden:
        regime_volume = (
            {
                "min_cessation_frames": 200,
                "min_other_regime_frames": 30,
                "exempt_regimes": V5_CESSATION_EXEMPT_REGIMES,
            }
            if args.scene_set == "v5-cessation"
            else None
        )
        path = write_golden_from_manifest(
            manifest, args.write_golden, config, output, regime_volume=regime_volume
        )
        print(f"Golden set {args.write_golden}: {path}")
    print(
        "\nSYNTHETIC-ONLY BASELINE. Real Site Zero footage supersedes this for "
        "product claims;\na scorecard from it must not be quoted externally."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
