"""Dataset registry: lanes, license snapshots, and a permanent blocklist.

Why this is code and not a policy document
------------------------------------------
A policy restrains nobody at 2 AM before a deadline. The registry does, because
every fetch, training run and calibration build goes through it, and it raises
rather than warns. The three failure modes it exists to prevent are all ones
that have actually happened to other companies:

- **Shipping a model fine-tuned on research-only data.** The license violation
  is permanent and the weights are the evidence. Lane R data therefore loads
  only through the eval harness; the training and calibration paths refuse it.
- **Building on retracted data.** DukeMTMC was withdrawn after an ethics
  scandal; MS-Celeb was withdrawn. Both, and their derivatives, are permanent
  ``blocked=True`` entries the registry knows by name, so a future fetch fails
  loudly with the retraction reason rather than quietly succeeding from a
  mirror.
- **Trusting a license class from memory.** Licenses change and recollections
  are wrong. Every entry ships with a ``hypothesis_class`` — explicitly a
  starting hypothesis — and nothing can be fetched until a human records a
  :class:`LicenseSnapshot` with a URL, a date and a hash of the text they
  actually read. When the upstream text changes later, the hash mismatch
  surfaces it.

The lanes
---------
======  ========================================  ==================================
Lane    Source                                    Allowed uses
======  ========================================  ==================================
``S``   Synthetic, generated by us, every asset   Everything: train, calibrate, eval
        in the stack commercially cleared
``R``   Research-licensed public datasets         Eval and model selection ONLY
``C``   Consented, self-collected (Site Zero,     Everything, and the only lane
        design partners under data-use contracts) admissible for INT8 calibration
======  ========================================  ==================================

Lane S is not automatically clean: several synthetic-human datasets are built
on SMPL body models whose commercial use needs a separate Meshcapade license.
Synthetic means "no consent debt", not "no license". The snapshot requirement
applies to lane S like everything else.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path
from types import FrameType
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

Lane = Literal["S", "R", "C"]

LANE_DESCRIPTIONS: dict[Lane, str] = {
    "S": "synthetic, generated by us — train/calibrate/eval",
    "R": "research-licensed public — EVAL ONLY, never trained on, never shipped",
    "C": "consented self-collected — train/calibrate/eval/demo",
}

# Module-global marker. A module on the training path declares
# ``IRON_TRAINING_PATH = True`` at top level; the registry's loaders walk the
# call stack looking for it. This makes "lane R imported into training" a
# runtime error at the data boundary rather than a review comment, regardless
# of how many layers of helper functions sit in between.
TRAINING_PATH_MARKER = "IRON_TRAINING_PATH"

# Permanent blocklist, in code rather than only in YAML: deleting a YAML entry
# must not unblock a retracted dataset. Keys are normalised names; matching is
# fuzzy on case, whitespace, dashes and underscores so "DukeMTMC-reID" and
# "dukemtmc_reid" both hit.
PERMANENT_BLOCKLIST: dict[str, str] = {
    "dukemtmc": (
        "RETRACTED by its creators in 2019 after an ethics investigation: "
        "footage of students captured without meaningful consent, and the "
        "dataset was used far beyond its stated terms. Do not fetch from "
        "mirrors; the retraction is the point, not an availability problem."
    ),
    "dukemtmcreid": (
        "RETRACTED by inheritance: a derivative of DukeMTMC, which was "
        "withdrawn after an ethics investigation. A crop of a non-consented "
        "recording is still a non-consented recording."
    ),
    "dukemtmcvideoreid": (
        "RETRACTED by inheritance: a derivative of the withdrawn DukeMTMC."
    ),
    "msceleb": (
        "Withdrawn by Microsoft in 2019: celebrity and non-celebrity faces "
        "scraped without consent. Widely mirrored; still withdrawn."
    ),
    "msceleb1m": ("Alias of MS-Celeb; withdrawn."),
}


class RegistryError(RuntimeError):
    """Base class for registry refusals."""


class BlockedDataset(RegistryError):
    """Raised for any operation on a permanently blocked dataset."""


class LicenseNotVerified(RegistryError):
    """Raised when an operation requires a license snapshot and none exists."""


class LaneViolation(RegistryError):
    """Raised when a dataset is used outside what its lane permits."""


class UnknownDataset(RegistryError):
    """Raised for a name the registry has never heard of.

    Deliberately an error rather than a permissive default: an unregistered
    dataset has no lane, and data with no lane has no permitted uses.
    """


def normalise(name: str) -> str:
    """Canonical key for fuzzy matching: lowercase, alphanumerics only."""
    return "".join(ch for ch in name.lower() if ch.isalnum())


class LicenseSnapshot(BaseModel):
    """A recorded act of a human reading the actual license text.

    The hash is of the text as read on the recorded date. It is diff-able
    evidence: when the upstream license changes, re-verification produces a
    different hash and the mismatch is visible instead of silent.
    """

    model_config = ConfigDict(frozen=True)

    url: str
    verified_date: date
    text_sha256: str
    verified_by: str = ""
    verified_class: str = ""
    """The license class as determined from the read text — which may differ
    from the entry's ``hypothesis_class``, and wins when it does."""


class DatasetEntry(BaseModel):
    """One dataset the project knows about."""

    model_config = ConfigDict(frozen=True)

    name: str
    lane: Lane
    subsystem: str = ""
    hypothesis_class: str = ""
    """License class as stated in the data-strategy document — from memory,
    explicitly a hypothesis, cleared only by a :class:`LicenseSnapshot`."""

    license_snapshot: LicenseSnapshot | None = None
    content_sha: str | None = None
    blocked: bool = False
    blocked_reason: str = ""
    notes: str = ""
    asset_clearance: list[dict[str, str]] = Field(default_factory=list)
    """Per-asset provenance for lane-S generators.

    Required in practice for synthetic data because "synthetic" is not a
    license: SMPL-derived human assets carry a commercial-use requirement
    that survives being rendered.
    """

    @property
    def verified(self) -> bool:
        return self.license_snapshot is not None


def _blocked_reason_for(name: str) -> str | None:
    return PERMANENT_BLOCKLIST.get(normalise(name))


def _calling_context_is_training() -> bool:
    """True when any frame on the stack belongs to a training-path module.

    Walks ``f_globals`` for :data:`TRAINING_PATH_MARKER`. Stack inspection is
    unusual, and used deliberately: the alternative is trusting every helper
    between a training entrypoint and the loader to forward a flag, and the
    2 AM failure mode is exactly someone adding a helper that does not.
    """
    frame: FrameType | None = sys._getframe(1)
    while frame is not None:
        if frame.f_globals.get(TRAINING_PATH_MARKER):
            return True
        frame = frame.f_back
    return False


class DatasetRegistry:
    """The registry: loaded from YAML, checked in code."""

    def __init__(self, entries: dict[str, DatasetEntry]) -> None:
        self._entries = entries

    @classmethod
    def load(cls, path: Path) -> "DatasetRegistry":
        """Load ``configs/datasets.yaml``.

        Raises:
            RegistryError: if the file is missing or malformed, or if an entry
                tries to register a permanently blocked name as unblocked —
                the in-code blocklist outranks the YAML precisely so that
                editing the YAML cannot unblock a retraction.
        """
        if not path.exists():
            raise RegistryError(f"dataset registry not found at {path}")
        payload: Any = yaml.safe_load(path.read_text()) or {}
        raw_entries = payload.get("datasets", [])
        if not isinstance(raw_entries, list):
            raise RegistryError(f"{path}: 'datasets' must be a list")

        entries: dict[str, DatasetEntry] = {}
        for raw in raw_entries:
            entry = DatasetEntry.model_validate(raw)
            reason = _blocked_reason_for(entry.name)
            if reason is not None and not entry.blocked:
                raise RegistryError(
                    f"{entry.name!r} is on the permanent blocklist and cannot "
                    f"be registered as unblocked: {reason}"
                )
            entries[normalise(entry.name)] = entry
        return cls(entries)

    # -- lookup -----------------------------------------------------------

    def entries(self) -> list[DatasetEntry]:
        return sorted(self._entries.values(), key=lambda e: e.name.lower())

    def get(self, name: str) -> DatasetEntry:
        """Look a dataset up, refusing blocked names before anything else.

        The blocklist check runs even for names absent from the YAML: a
        blocked dataset that someone removed from the registry file must stay
        blocked.
        """
        reason = _blocked_reason_for(name)
        key = normalise(name)
        entry = self._entries.get(key)
        if reason is not None or (entry is not None and entry.blocked):
            raise BlockedDataset(
                f"{name!r} is permanently blocked: "
                f"{reason or entry.blocked_reason if entry else reason}"
            )
        if entry is None:
            raise UnknownDataset(
                f"{name!r} is not in the dataset registry. Data with no "
                "registered lane has no permitted uses; add it to "
                "configs/datasets.yaml with a lane and a hypothesis class "
                "first."
            )
        return entry

    # -- enforcement ------------------------------------------------------

    def require_fetchable(self, name: str) -> DatasetEntry:
        """Gate for downloads: known, not blocked, license verified by a human.

        Raises:
            LicenseNotVerified: when no snapshot exists. The stated class in
                the strategy document is a hypothesis, and hypotheses do not
                authorise downloads.
        """
        entry = self.get(name)
        if entry.license_snapshot is None:
            raise LicenseNotVerified(
                f"{entry.name!r} has no license snapshot. A human must read "
                "the actual license text and record it "
                "(scripts/fetch_dataset.py --verify-license) before anything "
                f"is downloaded. Stated hypothesis class "
                f"{entry.hypothesis_class!r} is a starting point, not a "
                "clearance."
            )
        return entry

    def open_for_training(self, name: str) -> DatasetEntry:
        """Gate for the train/fine-tune/calibration paths: lanes S and C only.

        Raises:
            LaneViolation: for lane R. A model fine-tuned on research-only
                data and then sold is a license violation with the weights as
                evidence; there is no warn-and-continue for that.
        """
        entry = self.require_fetchable(name)
        if entry.lane == "R":
            raise LaneViolation(
                f"{entry.name!r} is lane R ({LANE_DESCRIPTIONS['R']}). It must "
                "never enter a training, fine-tuning or calibration path. Use "
                "it through the eval harness only."
            )
        return entry

    def open_for_eval(self, name: str) -> DatasetEntry:
        """Gate for the eval harness: any lane, but never from a training path.

        A lane-R loader imported into a training-path module raises here even
        though the *call* says "eval": the stack marker check is what catches
        an eval helper being repurposed as a training data feed.
        """
        entry = self.require_fetchable(name)
        if entry.lane == "R" and _calling_context_is_training():
            raise LaneViolation(
                f"{entry.name!r} is lane R and this call reaches it from a "
                f"module marked {TRAINING_PATH_MARKER}. Eval-only data cannot "
                "be loaded on a training path, whatever the loading function "
                "is called."
            )
        return entry
