"""Dataset registry: lanes, license snapshots, and a permanent blocklist.

Why this is code and not a policy document
------------------------------------------
A policy restrains nobody at 2 AM before a deadline. The registry does, because
every fetch, training run and calibration build goes through it, and it raises
rather than warns. The three failure modes it exists to prevent are all ones
that have actually happened to other companies:

- **Shipping a model fine-tuned on research-only data.** The license violation
  is permanent and the weights are the evidence. Lane R data therefore loads
  only through the eval harness; the training and calibration paths refuse it.
- **Building on retracted data.** DukeMTMC was withdrawn after an ethics
  scandal; MS-Celeb was withdrawn. Both, and their derivatives, are permanent
  ``blocked=True`` entries the registry knows by name, so a future fetch fails
  loudly with the retraction reason rather than quietly succeeding from a
  mirror.
- **Trusting a license class from memory.** Licenses change and recollections
  are wrong. Every entry ships with a ``hypothesis_class`` — explicitly a
  starting hypothesis — and nothing can be fetched until a human records a
  :class:`LicenseSnapshot` with a URL, a date and a hash of the text they
  actually read. When the upstream text changes later, the hash mismatch
  surfaces it.

The lanes
---------
- ``S`` — Synthetic, generated by us, every asset in the stack
  commercially cleared. Allowed: everything (train, calibrate, eval).
- ``R`` — Research-licensed public datasets. Allowed: eval and model
  selection ONLY.
- ``C`` — Consented, self-collected (Site Zero, design partners under
  data-use contracts). Allowed: everything, and the only lane admissible
  for INT8 calibration.
- ``C_pending_consent`` — Self-collected footage with NO consent record
  attached for the purpose at hand. Allowed: NOTHING — rejected by every
  training, calibration, and eval loader until a ``ConsentRecord`` is
  attached (Day 23).

Lane S is not automatically clean: several synthetic-human datasets are built
on SMPL body models whose commercial use needs a separate Meshcapade license.
Synthetic means "no consent debt", not "no license". The snapshot requirement
applies to lane S like everything else.

``C_pending_consent`` (Day 23) exists for a specific, real gap: an archive
recorded for one purpose (e.g. premises security) does not automatically
carry consent for a DIFFERENT purpose (AI development) — the DPDP Act,
2023 treats purpose as part of what consent covers, so a purpose change
generally needs its own notice and consent. Registering such an archive
as lane ``C`` outright would misrepresent it as already-consented; leaving
it out of the registry entirely would make it invisible rather than
correctly gated. ``C_pending_consent`` is the third state this project's
binary consent model (:mod:`scripts.ingest_capture`: refuse outright, or
proceed) did not have a name for: *known to exist, not yet usable, and
constructable/listable so the gap itself is a recorded, visible fact
rather than a silent absence.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path
from types import FrameType
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

Lane = Literal["S", "R", "C", "C_pending_consent"]

ConsentPosture = Literal["staged_actors", "public_cctv_no_consent", "unknown"]
"""Whether the PEOPLE ON CAMERA in a lane-R dataset were performers under a
research programme, or unconsenting subjects of real, uncontrolled
surveillance footage (Day 35) — a distinction this project had left
implicit for thirty days despite it mattering as much as ``hypothesis_class``
does for license. Deliberately separate from two adjacent concepts it is
easy to conflate with:

- ``hypothesis_class`` / :class:`LicenseSnapshot` govern the LICENSE on the
  recording — who may copy, redistribute, or train on it. A dataset can be
  perfectly clear on license (public research release) while its subjects
  never consented to being filmed at all (``public_cctv_no_consent``); the
  two questions are independent and a clean license snapshot answers
  neither.
- :class:`ConsentRecord` is THIS PROJECT'S OWN consent basis for lane
  ``C``/``C_pending_consent`` capture. ``consent_posture`` instead
  describes a THIRD PARTY dataset's own subjects, for lane R specifically
  — nothing this project did or can retroactively fix, only something it
  must not misrepresent by omission.

Like ``hypothesis_class``, a value here is a recorded hypothesis from
public documentation and project memory, not an independently re-verified
fact — ``unknown`` is the honest default whenever that hypothesis is not
solid, including for non-people-centric datasets (scene/depth scans) where
the staged/uncontrolled distinction does not obviously apply. ``None``
(the field's default) is reserved for lanes where the concept is genuinely
inapplicable in a different way — lane S (no real subjects at all, or the
subject question is answered by ``asset_clearance`` instead) and lane
C/C_pending_consent (governed by ``consent_record``, not this field)."""

Hosting = Literal["huggingface", "direct_url", "other", "unknown"]
"""HOW a dataset's canonical page is hosted — a fourth axis, orthogonal to
the other three the registry already tracks:

- ``hypothesis_class`` / :class:`LicenseSnapshot` — COPYRIGHT.
- :data:`ConsentPosture` / :class:`ConsentRecord` — SUBJECT CONSENT.
- :class:`DeploymentScopeRestriction` — DEPLOYMENT-USE SCOPE.
- ``hosting`` — none of those. It answers a purely mechanical question a
  license read cannot: is the URL a dataset's terms live at a STATIC file
  (a GitHub ``LICENSE``, safe to ``urlopen`` and hash directly), or a
  SERVER-RENDERED page that can embed per-request-volatile state around
  otherwise-stable text (Day 39, found on CHIRLA's HuggingFace dataset
  card — two fetches of the same unchanged license text minutes apart
  hashed differently because the page also carries live download/like
  counts and a ``lastModified`` timestamp)? Getting this wrong does not
  misjudge a license; it makes ``LicenseSnapshot.text_sha256`` noise, which
  is worse than an honest failure because it look like recorded evidence.

Read by :func:`scripts.fetch_dataset.verify_license` to choose a
verification strategy BEFORE any URL is touched — the routing is this
typed field, never a domain string sniffed out of ``--license-url`` deep
inside the function body, so a HuggingFace-hosted entry cannot silently
fall through to the naive whole-response hash by an unclassified URL
shape.

``"unknown"`` is the honest default, the same convention
:data:`ConsentPosture` uses — most of this registry's 63 entries have
never had their actual hosting mechanism confirmed (see
``docs/registry_deployment_scope_audit.md``, the same audit that will
eventually do this classification too). ``"direct_url"`` is a static file
already safe for the existing ``urlopen``-and-hash path (MEVA's tarball
license is the model case). ``"other"`` is reserved for a hosting
mechanism that is neither — recorded so a human classifying an entry is
never forced to mis-pick between the two real categories just because a
third option did not exist."""

LANE_DESCRIPTIONS: dict[Lane, str] = {
    "S": "synthetic, generated by us — train/calibrate/eval",
    "R": "research-licensed public — EVAL ONLY, never trained on, never shipped",
    "C": "consented self-collected — train/calibrate/eval/demo",
    "C_pending_consent": (
        "self-collected, no consent record attached for this purpose — "
        "REJECTED everywhere until a ConsentRecord is attached (Day 23)"
    ),
}

# Module-global marker. A module on the training path declares
# ``IRON_TRAINING_PATH = True`` at top level; the registry's loaders walk the
# call stack looking for it. This makes "lane R imported into training" a
# runtime error at the data boundary rather than a review comment, regardless
# of how many layers of helper functions sit in between.
TRAINING_PATH_MARKER = "IRON_TRAINING_PATH"

# Permanent blocklist, in code rather than only in YAML: deleting a YAML entry
# must not unblock a retracted dataset. Keys are normalised names; matching is
# fuzzy on case, whitespace, dashes and underscores so "DukeMTMC-reID" and
# "dukemtmc_reid" both hit.
PERMANENT_BLOCKLIST: dict[str, str] = {
    "dukemtmc": (
        "RETRACTED by its creators in 2019 after an ethics investigation: "
        "footage of students captured without meaningful consent, and the "
        "dataset was used far beyond its stated terms. Do not fetch from "
        "mirrors; the retraction is the point, not an availability problem."
    ),
    "dukemtmcreid": (
        "RETRACTED by inheritance: a derivative of DukeMTMC, which was "
        "withdrawn after an ethics investigation. A crop of a non-consented "
        "recording is still a non-consented recording."
    ),
    "dukemtmcvideoreid": (
        "RETRACTED by inheritance: a derivative of the withdrawn DukeMTMC."
    ),
    "msceleb": (
        "Withdrawn by Microsoft in 2019: celebrity and non-celebrity faces "
        "scraped without consent. Widely mirrored; still withdrawn."
    ),
    "msceleb1m": ("Alias of MS-Celeb; withdrawn."),
}


class RegistryError(RuntimeError):
    """Base class for registry refusals."""


class BlockedDataset(RegistryError):
    """Raised for any operation on a permanently blocked dataset."""


class LicenseNotVerified(RegistryError):
    """Raised when an operation requires a license snapshot and none exists."""


class LaneViolation(RegistryError):
    """Raised when a dataset is used outside what its lane permits."""


class DeploymentScopeUnresolved(RegistryError):
    """Raised when a report or document-generation path asks to cite a
    dataset's results for a product- or capability-level claim, and the
    entry carries a :class:`DeploymentScopeRestriction` whose ``resolved``
    flag is still ``False``.

    Deliberately distinct from :class:`LaneViolation` /
    :class:`LicenseNotVerified`: those gate whether data may be fetched or
    scored at all (copyright, lane). This gates whether a downstream
    deployment-scope restriction — independent of copyright, independent of
    subject consent — has actually been read and closed out by a human
    before its results back a claim about the product. A dataset can pass
    every other gate in this module and still trip this one.
    """


class UnknownDataset(RegistryError):
    """Raised for a name the registry has never heard of.

    Deliberately an error rather than a permissive default: an unregistered
    dataset has no lane, and data with no lane has no permitted uses.
    """


def normalise(name: str) -> str:
    """Canonical key for fuzzy matching: lowercase, alphanumerics only."""
    return "".join(ch for ch in name.lower() if ch.isalnum())


class LicenseSnapshot(BaseModel):
    """A recorded act of a human reading the actual license text.

    The hash is of the text as read on the recorded date. It is diff-able
    evidence: when the upstream license changes, re-verification produces a
    different hash and the mismatch is visible instead of silent.
    """

    model_config = ConfigDict(frozen=True)

    url: str
    verified_date: date
    text_sha256: str
    verified_by: str = ""
    verified_class: str = ""
    """The license class as determined from the read text — which may differ
    from the entry's ``hypothesis_class``, and wins when it does."""
    resolved_commit_sha: str | None = None
    """For ``hosting: huggingface`` entries only: the exact commit ``main``
    resolved to at verification time, mirroring this project's
    ``twin_rev``/``graph_rev`` pinning discipline — ``text_sha256`` is the
    hash of ``/raw/<resolved_commit_sha>/<path>`` at THIS commit, not of
    whatever ``main`` happens to point at when someone re-reads it later.
    Re-verifying against the same commit must reproduce the same hash; only
    a genuinely new commit should ever produce a different one. ``None``
    for every non-HuggingFace snapshot, where the underlying URL is already
    a static file with no revision concept."""


class DeploymentScopeRestriction(BaseModel):
    """A downstream deployment-scope restriction stated by a dataset's own
    terms, discovered Day 38 on CHIRLA's HuggingFace card and structurally
    distinct from the registry's other two legal dimensions:

    - :class:`LicenseSnapshot` / ``hypothesis_class`` govern COPYRIGHT — who
      may copy, redistribute, or train on the recording.
    - :data:`ConsentPosture` / :class:`ConsentRecord` govern SUBJECT
      CONSENT — whether the people on camera agreed to being filmed.
    - This class governs neither: it is a restriction the dataset's own
      terms place on HOW its data may be USED once obtained, independent of
      copyright and independent of whether the subjects consented. A
      dataset can score cleanly on both other axes and still carry this
      kind of restriction — CHIRLA does (CC-BY-4.0, IRB-approved unrestricted
      consent) while its HuggingFace card separately states: "Any
      deployment aimed at surveillance, identification, or monitoring of
      real people without explicit consent or where it violates privacy or
      law."

    ``resolved`` defaults to ``False`` and nothing in this module ever sets
    it ``True`` on its own judgment: two readings of a clause like CHIRLA's
    carry materially different consequences (narrow: permits use if the
    DEPLOYED system has its own valid consent architecture; broad: excludes
    any surveillance/identification/monitoring product regardless of
    deployment consent), and choosing between them is a legal
    interpretation — see
    :meth:`DatasetRegistry.require_product_claim_clearance`, the only place
    this field is read, and ``docs/blocker_ledger.yaml``'s
    ``chirla_deployment_scope_legal_review`` entry.
    """

    model_config = ConfigDict(frozen=True)

    text: str | None = None
    """Verbatim quote of the restriction, never a paraphrase — a summary
    can silently narrow or broaden a legal clause; the exact text is the
    only thing a reviewing human should trust."""
    source: str = ""
    """Exact URL/host and retrieval date the quote was read from."""
    resolved: bool = False
    resolution: str | None = None
    """Who resolved this and how — null until a human (counsel, per
    :class:`RegistryError`'s discipline elsewhere in this module) actually
    does so. Never set by inference from how clean the rest of an entry's
    license/consent fields look."""


class ConsentRecord(BaseModel):
    """A recorded consent basis for a lane ``C_pending_consent`` archive,
    attached to unlock it (Day 23) — the same role :class:`LicenseSnapshot`
    plays for a lane-R ``hypothesis_class``, applied to consent instead of
    license. Mirrors :class:`scripts.ingest_capture.ConsentRecord`'s shape
    (``subjects``, ``captured_on``) for a fresh capture; this one additionally
    names WHY it covers the specific purpose being unblocked, since an
    archive's original consent basis (if any) may have covered a different
    purpose than the one now being requested.
    """

    model_config = ConfigDict(frozen=True)

    path: str
    sha: str
    subjects: int
    captured_on: date
    recorded_by: str = ""
    purpose_note: str = ""
    """Why this consent basis covers the NEW purpose being unblocked — e.g.
    a premises-security archive newly consented for AI development must
    say so explicitly; a blank purpose_note on an attached record is a
    review smell, not proof of nothing to explain."""


class DatasetEntry(BaseModel):
    """One dataset the project knows about."""

    model_config = ConfigDict(frozen=True)

    name: str
    lane: Lane
    subsystem: str = ""
    hypothesis_class: str = ""
    """License class as stated in the data-strategy document — from memory,
    explicitly a hypothesis, cleared only by a :class:`LicenseSnapshot`."""

    license_snapshot: LicenseSnapshot | None = None
    consent_posture: ConsentPosture | None = None
    """Whether this entry's real-world subjects were staged performers or
    unconsenting subjects of real surveillance — see :data:`ConsentPosture`.
    Backfilled Day 35 on every pre-existing lane-R entry, not only ones
    added that day; ``None`` for lanes where it does not apply."""
    consent_record: ConsentRecord | None = None
    """Required before ANY loader (training, calibration, eval) accepts a
    lane ``C_pending_consent`` entry — see
    :meth:`DatasetRegistry._require_consent`. Unused for every other lane;
    lane ``C``'s consent is assumed already established by the time an
    entry is registered under that lane rather than
    ``C_pending_consent``."""
    deployment_scope_restriction: DeploymentScopeRestriction | None = None
    """A downstream deployment-scope restriction stated by the dataset's
    own terms — see :class:`DeploymentScopeRestriction` for why this is a
    third, independent axis from ``hypothesis_class``/``license_snapshot``
    (copyright) and ``consent_posture``/``consent_record`` (subject
    consent). ``None`` for the overwhelming majority of entries, not
    because they are known clear on this axis but because nobody has read
    their non-GitHub hosting pages to find out — see
    ``docs/registry_deployment_scope_audit.md``."""
    hosting: Hosting = "unknown"
    """How this entry's canonical page is hosted — see :data:`Hosting` for
    why this is a fourth axis, independent of license/consent/deployment-
    scope, and why :func:`scripts.fetch_dataset.verify_license` routes on
    it rather than guessing from the URL. Backfilled Day 39 on CHIRLA only
    (``"huggingface"``, the entry that exposed why this field needs to
    exist); every other entry defaults ``"unknown"`` pending the same kind
    of registry-wide reaudit ``deployment_scope_restriction`` got on Day
    38 — not attempted today."""
    validity_matrix_cell: str = ""
    """Which (capability, domain) cell of scripts/validity_matrix.py's
    grid this dataset would fill if verified and used for eval — e.g.
    'appearance_semantics x indoor-surveillance-activity'. One line,
    stated even for an unverified/unfetched entry, so the registry answers
    not just "what is this" but "what would it actually measure"."""
    content_sha: str | None = None
    blocked: bool = False
    blocked_reason: str = ""
    notes: str = ""
    asset_clearance: list[dict[str, str]] = Field(default_factory=list)
    """Per-asset provenance for lane-S generators.

    Required in practice for synthetic data because "synthetic" is not a
    license: SMPL-derived human assets carry a commercial-use requirement
    that survives being rendered.
    """

    @property
    def verified(self) -> bool:
        return self.license_snapshot is not None


def _blocked_reason_for(name: str) -> str | None:
    return PERMANENT_BLOCKLIST.get(normalise(name))


def _calling_context_is_training() -> bool:
    """True when any frame on the stack belongs to a training-path module.

    Walks ``f_globals`` for :data:`TRAINING_PATH_MARKER`. Stack inspection is
    unusual, and used deliberately: the alternative is trusting every helper
    between a training entrypoint and the loader to forward a flag, and the
    2 AM failure mode is exactly someone adding a helper that does not.
    """
    frame: FrameType | None = sys._getframe(1)
    while frame is not None:
        if frame.f_globals.get(TRAINING_PATH_MARKER):
            return True
        frame = frame.f_back
    return False


class DatasetRegistry:
    """The registry: loaded from YAML, checked in code."""

    def __init__(self, entries: dict[str, DatasetEntry]) -> None:
        self._entries = entries

    @classmethod
    def load(cls, path: Path) -> "DatasetRegistry":
        """Load ``configs/datasets.yaml``.

        Raises:
            RegistryError: if the file is missing or malformed, or if an entry
                tries to register a permanently blocked name as unblocked —
                the in-code blocklist outranks the YAML precisely so that
                editing the YAML cannot unblock a retraction.
        """
        if not path.exists():
            raise RegistryError(f"dataset registry not found at {path}")
        payload: Any = yaml.safe_load(path.read_text()) or {}
        raw_entries = payload.get("datasets", [])
        if not isinstance(raw_entries, list):
            raise RegistryError(f"{path}: 'datasets' must be a list")

        entries: dict[str, DatasetEntry] = {}
        for raw in raw_entries:
            entry = DatasetEntry.model_validate(raw)
            reason = _blocked_reason_for(entry.name)
            if reason is not None and not entry.blocked:
                raise RegistryError(
                    f"{entry.name!r} is on the permanent blocklist and cannot "
                    f"be registered as unblocked: {reason}"
                )
            entries[normalise(entry.name)] = entry
        return cls(entries)

    # -- lookup -----------------------------------------------------------

    def entries(self) -> list[DatasetEntry]:
        return sorted(self._entries.values(), key=lambda e: e.name.lower())

    def get(self, name: str) -> DatasetEntry:
        """Look a dataset up, refusing blocked names before anything else.

        The blocklist check runs even for names absent from the YAML: a
        blocked dataset that someone removed from the registry file must stay
        blocked.
        """
        reason = _blocked_reason_for(name)
        key = normalise(name)
        entry = self._entries.get(key)
        if reason is not None or (entry is not None and entry.blocked):
            raise BlockedDataset(
                f"{name!r} is permanently blocked: "
                f"{reason or entry.blocked_reason if entry else reason}"
            )
        if entry is None:
            raise UnknownDataset(
                f"{name!r} is not in the dataset registry. Data with no "
                "registered lane has no permitted uses; add it to "
                "configs/datasets.yaml with a lane and a hypothesis class "
                "first."
            )
        return entry

    # -- enforcement ------------------------------------------------------

    def require_fetchable(self, name: str) -> DatasetEntry:
        """Gate for downloads: known, not blocked, license verified by a human.

        Raises:
            LicenseNotVerified: when no snapshot exists. The stated class in
                the strategy document is a hypothesis, and hypotheses do not
                authorise downloads.
        """
        entry = self.get(name)
        if entry.license_snapshot is None:
            raise LicenseNotVerified(
                f"{entry.name!r} has no license snapshot. A human must read "
                "the actual license text and record it "
                "(scripts/fetch_dataset.py --verify-license) before anything "
                f"is downloaded. Stated hypothesis class "
                f"{entry.hypothesis_class!r} is a starting point, not a "
                "clearance."
            )
        return entry

    def _require_consent(self, entry: DatasetEntry) -> None:
        """Day 23: the ``C_pending_consent`` gate, checked BEFORE
        :meth:`require_fetchable`'s license check -- a self-collected
        archive has no third-party license to verify, so routing it
        through the license-verification error first would misname why it
        was actually rejected.

        Raises:
            LaneViolation: if ``entry.lane == "C_pending_consent"`` and no
                :class:`ConsentRecord` is attached. Every other lane is a
                no-op here.
        """
        if entry.lane == "C_pending_consent" and entry.consent_record is None:
            raise LaneViolation(
                f"{entry.name!r} is lane C_pending_consent: self-collected "
                "footage with no consent record attached for this purpose. "
                "A recording purpose (e.g. premises security) does not "
                "carry over to a new purpose (e.g. AI development) under "
                "the DPDP Act, 2023 -- that generally needs its own notice "
                "and consent. Attach a ConsentRecord to this entry's "
                "consent_record field before it may be used for training, "
                "calibration, or eval."
            )

    def open_for_training(self, name: str) -> DatasetEntry:
        """Gate for the train/fine-tune/calibration paths: lanes S and C only.

        Raises:
            LaneViolation: for lane R, or for lane C_pending_consent with
                no consent record attached. A model fine-tuned on
                research-only data and then sold is a license violation
                with the weights as evidence; a model trained on
                non-consented footage of real people is the same shape of
                irreversible mistake — there is no warn-and-continue for
                either.
        """
        self._require_consent(self.get(name))
        entry = self.require_fetchable(name)
        if entry.lane == "R":
            raise LaneViolation(
                f"{entry.name!r} is lane R ({LANE_DESCRIPTIONS['R']}). It must "
                "never enter a training, fine-tuning or calibration path. Use "
                "it through the eval harness only."
            )
        return entry

    def open_for_eval(self, name: str) -> DatasetEntry:
        """Gate for the eval harness: any lane, but never from a training path.

        A lane-R loader imported into a training-path module raises here even
        though the *call* says "eval": the stack marker check is what catches
        an eval helper being repurposed as a training data feed.

        Raises:
            LaneViolation: for lane R reached from a training-marked
                module, or for lane C_pending_consent with no consent
                record attached — REJECTED here too, unlike lane R:
                non-consented footage of real people has no basis for
                even an internal eval number, the same reasoning
                :func:`scripts.ingest_capture.ConsentRecord.load` already
                applies at ingest time.
        """
        self._require_consent(self.get(name))
        entry = self.require_fetchable(name)
        if entry.lane == "R" and _calling_context_is_training():
            raise LaneViolation(
                f"{entry.name!r} is lane R and this call reaches it from a "
                f"module marked {TRAINING_PATH_MARKER}. Eval-only data cannot "
                "be loaded on a training path, whatever the loading function "
                "is called."
            )
        return entry

    def require_product_claim_clearance(self, name: str) -> DatasetEntry:
        """Gate for report/document-generation paths that would cite a
        dataset's results for a product- or capability-level claim, as
        opposed to pure internal algorithm benchmarking (which goes through
        :meth:`open_for_eval` alone and is entirely unaffected by this
        method — CHIRLA may still be benchmarked internally the moment its
        license is verified, regardless of how this gate resolves).

        Deliberately orthogonal to lane/license enforcement: a caller that
        also wants those checks calls :meth:`open_for_eval` (or
        :meth:`open_for_training`) itself; this method's only job is
        surfacing an unresolved :class:`DeploymentScopeRestriction` rather
        than letting it pass through silently into a claim.

        Raises:
            DeploymentScopeUnresolved: if the entry carries a
                ``deployment_scope_restriction`` and its ``resolved`` flag
                is still ``False``.

        **Bounded, explicitly** (Day 38): this only fires for a call site
        that actually calls it. Nothing in this codebase currently forces
        every future report- or document-writing code path through here,
        and nothing here can stop a human from typing a product claim
        directly into prose (``FOUNDATION_REPORT.md`` and similar) by hand.
        That is a process gap this mechanism cannot close by itself — see
        ``docs/blocker_ledger.yaml``'s ``chirla_deployment_scope_legal_
        review`` entry and FOUNDATION_REPORT.md's Day-38 section for that
        limit stated in full, not implied away.
        """
        entry = self.get(name)
        restriction = entry.deployment_scope_restriction
        if restriction is not None and not restriction.resolved:
            raise DeploymentScopeUnresolved(
                f"{entry.name!r} carries an unresolved deployment_scope_"
                f"restriction and cannot back a product- or capability-"
                f"level claim: {restriction.text!r} (source: "
                f"{restriction.source}). This is a legal interpretation "
                "question, not an engineering one — resolve it (counsel "
                "review) and record entry.deployment_scope_restriction."
                "resolution before citing this dataset's results outside "
                "pure internal algorithm benchmarking."
            )
        return entry
